import type { TaxiZone } from "./types";

const accessedAt = "2026-06-16T00:00:00-04:00";

const vipaOfficialSource = {
  label: "VIPA airport and seaport ground transportation",
  sourceType: "vipa_official" as const,
  effectiveDate: "2026-06-16",
  accessedAt,
};

const sttSource = {
  label: "Published 2022 St. Thomas taxi rate sheet capture",
  sourceType: "secondary_published_sheet" as const,
  effectiveDate: "2022-10-24",
  accessedAt,
};

const stjSource = {
  label: "Published 2022 St. John taxi rate sheet capture",
  sourceType: "secondary_published_sheet" as const,
  effectiveDate: "2022-10-24",
  accessedAt,
};

const stxSource = {
  label: "Published 2022 St. Croix taxi rate sheet capture",
  sourceType: "secondary_published_sheet" as const,
  effectiveDate: "2022-10-24",
  accessedAt,
};

const manualSource = {
  label: "Manual mobility anchor seed",
  sourceType: "manual_admin_entry" as const,
  accessedAt,
};

function zone(params: TaxiZone): TaxiZone {
  return params;
}

export const taxiZones: TaxiZone[] = [
  zone({
    id: "stt_airport",
    island: "stt",
    slug: "cyril-e-king-airport",
    displayName: "Cyril E. King Airport",
    zoneType: "airport",
    aliases: ["airport", "stt airport", "cyril e king", "cek", "ceka", "lindbergh", "lindbergh bay"],
    estateNames: ["Lindbergh Bay", "Crown Bay"],
    dispatchAssociationId: "stt_vi_taxi_association",
    source: vipaOfficialSource,
    reviewStatus: "verified_official",
  }),
  zone({
    id: "stt_charlotte_amalie",
    island: "stt",
    slug: "charlotte-amalie",
    displayName: "Charlotte Amalie",
    zoneType: "town",
    aliases: ["charlotte amalie", "town", "downtown", "main street", "waterfront", "market square", "fort christian"],
    estateNames: ["Charlotte Amalie", "Hospital Ground", "Kings Quarter", "Queens Quarter"],
    source: sttSource,
    reviewStatus: "verified_operational",
  }),
  zone({
    id: "stt_havensight",
    island: "stt",
    slug: "havensight-wico",
    displayName: "Havensight / WICO",
    zoneType: "port",
    aliases: ["havensight", "wico", "wico dock", "cruise port", "cruise dock", "havensight mall", "long bay"],
    estateNames: ["Havensight", "Long Bay", "Estate Thomas"],
    dispatchAssociationId: "wico",
    source: vipaOfficialSource,
    reviewStatus: "verified_official",
  }),
  zone({
    id: "stt_crown_bay",
    island: "stt",
    slug: "crown-bay",
    displayName: "Crown Bay",
    zoneType: "port",
    aliases: ["crown bay", "crown bay cruise port", "crown bay dock", "subbase", "crown bay marina"],
    estateNames: ["Crown Bay", "Subbase", "Nisky"],
    dispatchAssociationId: "stt_taxi_association",
    source: vipaOfficialSource,
    reviewStatus: "verified_official",
  }),
  zone({
    id: "stt_frenchtown",
    island: "stt",
    slug: "frenchtown",
    displayName: "Frenchtown",
    zoneType: "estate_area",
    aliases: ["frenchtown", "french town", "frenchtown marina"],
    estateNames: ["Frenchtown", "Santa Maria", "Nisky"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_red_hook",
    island: "stt",
    slug: "red-hook",
    displayName: "Red Hook",
    zoneType: "port",
    aliases: ["red hook", "redhook", "red hook ferry", "ferry terminal", "urman victor fredericks", "american yacht harbor", "ayh"],
    estateNames: ["Red Hook", "Nazareth", "Frydenhoj", "Frydendal"],
    dispatchAssociationId: "stt_east_end_taxi",
    source: vipaOfficialSource,
    reviewStatus: "verified_official",
  }),
  zone({
    id: "stt_tutu",
    island: "stt",
    slug: "tutu-annas-retreat",
    displayName: "Tutu / Anna's Retreat",
    zoneType: "estate_area",
    aliases: ["tutu", "anna's retreat", "annas retreat", "tutu park mall", "tutu mall", "tutu valley"],
    estateNames: ["Tutu", "Anna's Retreat", "Annas Retreat"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_magens_bay",
    island: "stt",
    slug: "magens-bay",
    displayName: "Magens Bay",
    zoneType: "landmark",
    aliases: ["magens", "magens bay", "magens bay beach", "magen's bay", "peterborg"],
    estateNames: ["Magens Bay", "Peterborg"],
    source: sttSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_smith_bay",
    island: "stt",
    slug: "smith-bay",
    displayName: "Smith Bay",
    zoneType: "estate_area",
    aliases: ["smith bay", "estate smith bay", "lindquist", "lindquist beach", "smith bay park"],
    estateNames: ["Smith Bay"],
    source: sttSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_coki",
    island: "stt",
    slug: "coki-point",
    displayName: "Coki Point / Coral World",
    zoneType: "landmark",
    aliases: ["coki", "coki point", "coki beach", "coral world", "coral world ocean park"],
    estateNames: ["Smith Bay"],
    source: sttSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_secret_harbour",
    island: "stt",
    slug: "secret-harbour",
    displayName: "Secret Harbour",
    zoneType: "hotel_cluster",
    aliases: ["secret harbour", "secret harbor", "secret harbour beach", "secret harbour resort", "nazareth bay", "vessup"],
    estateNames: ["Nazareth", "Vessup"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_sapphire",
    island: "stt",
    slug: "sapphire-beach",
    displayName: "Sapphire Beach",
    zoneType: "hotel_cluster",
    aliases: ["sapphire", "sapphire beach", "sapphire resort", "sapphire beach resort"],
    estateNames: ["Smith Bay", "Nazareth"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_bolongo",
    island: "stt",
    slug: "bolongo",
    displayName: "Bolongo",
    zoneType: "hotel_cluster",
    aliases: ["bolongo", "bolongo bay", "bolongo bay beach resort"],
    estateNames: ["Bolongo"],
    source: sttSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_frenchmans_reef",
    island: "stt",
    slug: "frenchmans-reef",
    displayName: "Frenchman's Reef / Morning Star",
    zoneType: "hotel_cluster",
    aliases: ["frenchman's reef", "frenchmans reef", "morning star", "morningstar", "morning star beach", "frenchman bay"],
    estateNames: ["Frenchman Bay", "Bakkero"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_mafolie",
    island: "stt",
    slug: "mafolie",
    displayName: "Mafolie",
    zoneType: "estate_area",
    aliases: ["mafolie", "mafolie hotel", "solberg"],
    estateNames: ["Mafolie", "Solberg"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_mountain_top",
    island: "stt",
    slug: "mountain-top",
    displayName: "Mountain Top",
    zoneType: "landmark",
    aliases: ["mountain top", "mountaintop", "st peter", "saint peter", "drake seat", "drake's seat"],
    estateNames: ["St. Peter", "Saint Peter", "Bonne Resolution", "Mafolie"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_brewers_bay",
    island: "stt",
    slug: "brewers-bay",
    displayName: "Brewers Bay / UVI",
    zoneType: "landmark",
    aliases: ["brewers", "brewers bay", "brewer's bay", "brewers beach", "uvi", "university of the virgin islands"],
    estateNames: ["John Brewers Bay", "Brewers Bay"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_hull_bay",
    island: "stt",
    slug: "hull-bay",
    displayName: "Hull Bay",
    zoneType: "landmark",
    aliases: ["hull bay", "hull bay beach", "hull", "dorothea"],
    estateNames: ["Hull", "Dorothea"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_west_end",
    island: "stt",
    slug: "west-end",
    displayName: "West End / Bordeaux",
    zoneType: "estate_area",
    aliases: ["west end", "bordeaux", "botany bay", "santa maria", "caret bay"],
    estateNames: ["Bordeaux", "Botany Bay", "Santa Maria", "Careenage"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stt_water_island_ferry",
    island: "stt",
    slug: "water-island-ferry",
    displayName: "Water Island Ferry",
    zoneType: "port",
    aliases: ["water island ferry", "water island ferry terminal", "tickles dock", "crown bay ferry"],
    estateNames: ["Crown Bay", "Subbase"],
    source: manualSource,
    reviewStatus: "needs_review",
  }),

  zone({
    id: "stj_cruz_bay",
    island: "stj",
    slug: "cruz-bay",
    displayName: "Cruz Bay",
    zoneType: "port",
    aliases: ["cruz bay", "cruz bay dock", "cruz bay ferry", "mongoose junction", "st john ferry"],
    estateNames: ["Cruz Bay", "Enighed", "Great Cruz Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_coral_bay",
    island: "stj",
    slug: "coral-bay",
    displayName: "Coral Bay",
    zoneType: "town",
    aliases: ["coral bay", "coral harbor", "johns folly"],
    estateNames: ["Coral Bay", "Emmaus", "Carolina"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_trunk_bay",
    island: "stj",
    slug: "trunk-bay",
    displayName: "Trunk Bay",
    zoneType: "landmark",
    aliases: ["trunk bay", "trunk bay beach", "trunk"],
    estateNames: ["Trunk Bay", "Maho Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_caneel_bay",
    island: "stj",
    slug: "caneel-bay",
    displayName: "Caneel Bay",
    zoneType: "hotel_cluster",
    aliases: ["caneel", "caneel bay", "caneel bay resort"],
    estateNames: ["Caneel Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_chocolate_hole",
    island: "stj",
    slug: "chocolate-hole",
    displayName: "Chocolate Hole",
    zoneType: "estate_area",
    aliases: ["chocolate hole", "chocolate hole bay"],
    estateNames: ["Chocolate Hole", "Great Cruz Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_westin",
    island: "stj",
    slug: "westin-st-john",
    displayName: "Westin St. John",
    zoneType: "hotel_cluster",
    aliases: ["westin", "westin st john", "westin resort", "great cruz bay resort"],
    estateNames: ["Great Cruz Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_great_cruz_bay",
    island: "stj",
    slug: "great-cruz-bay",
    displayName: "Great Cruz Bay",
    zoneType: "estate_area",
    aliases: ["great cruz bay", "great cruz"],
    estateNames: ["Great Cruz Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_cinnamon_bay",
    island: "stj",
    slug: "cinnamon-bay",
    displayName: "Cinnamon Bay",
    zoneType: "landmark",
    aliases: ["cinnamon", "cinnamon bay", "cinnamon bay campground"],
    estateNames: ["Cinnamon Bay", "Maho Bay"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_maho_bay",
    island: "stj",
    slug: "maho-bay",
    displayName: "Maho Bay",
    zoneType: "landmark",
    aliases: ["maho", "maho bay", "maho bay beach"],
    estateNames: ["Maho Bay", "Annaberg"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_leinster_bay",
    island: "stj",
    slug: "leinster-bay",
    displayName: "Leinster Bay / Annaberg",
    zoneType: "landmark",
    aliases: ["leinster", "leinster bay", "annaberg", "annaberg ruins", "waterlemon cay"],
    estateNames: ["Leinster Bay", "Annaberg"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stj_salt_pond",
    island: "stj",
    slug: "salt-pond",
    displayName: "Salt Pond",
    zoneType: "landmark",
    aliases: ["salt pond", "salt pond bay", "ram head", "drunk bay"],
    estateNames: ["Salt Pond", "Concordia", "Lameshur"],
    source: stjSource,
    reviewStatus: "needs_review",
  }),

  zone({
    id: "stx_airport",
    island: "stx",
    slug: "henry-e-rohlsen-airport",
    displayName: "Henry E. Rohlsen Airport",
    zoneType: "airport",
    aliases: ["stx airport", "airport", "henry e rohlsen", "rohlsen airport", "alexander hamilton airport"],
    estateNames: ["Airport", "Manning Bay"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_christiansted",
    island: "stx",
    slug: "christiansted",
    displayName: "Christiansted",
    zoneType: "town",
    aliases: ["christiansted", "town christiansted", "christiansted boardwalk", "king street christiansted"],
    estateNames: ["Christiansted", "Company", "King", "Queen"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_frederiksted",
    island: "stx",
    slug: "frederiksted",
    displayName: "Frederiksted",
    zoneType: "town",
    aliases: ["frederiksted", "frederiksted pier", "frederiksted cruise pier", "fort frederik", "west end stx"],
    estateNames: ["Frederiksted", "Two Brothers", "William's Delight"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_sunny_isle",
    island: "stx",
    slug: "sunny-isle",
    displayName: "Sunny Isle",
    zoneType: "estate_area",
    aliases: ["sunny isle", "sunnyisle", "sunny isle shopping center"],
    estateNames: ["Sion Farm", "Barren Spot"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_golden_rock",
    island: "stx",
    slug: "golden-rock",
    displayName: "Golden Rock",
    zoneType: "estate_area",
    aliases: ["golden rock", "orange grove"],
    estateNames: ["Golden Rock", "Orange Grove"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_gallows_bay",
    island: "stx",
    slug: "gallows-bay",
    displayName: "Gallows Bay",
    zoneType: "port",
    aliases: ["gallows bay", "gallows bay dock", "christiansted ferry"],
    estateNames: ["Gallows Bay", "Christiansted"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_buccaneer",
    island: "stx",
    slug: "buccaneer",
    displayName: "Buccaneer",
    zoneType: "hotel_cluster",
    aliases: ["buccaneer", "the buccaneer", "buccaneer hotel"],
    estateNames: ["Shoys", "Buccaneer"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_cane_bay",
    island: "stx",
    slug: "cane-bay",
    displayName: "Cane Bay",
    zoneType: "landmark",
    aliases: ["cane bay", "cane bay beach", "north shore"],
    estateNames: ["Cane Bay", "La Vallee"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_kingshill",
    island: "stx",
    slug: "kingshill",
    displayName: "Kingshill",
    zoneType: "estate_area",
    aliases: ["kingshill", "kings hill", "central high"],
    estateNames: ["Kingshill", "Glynn"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_mid_island",
    island: "stx",
    slug: "mid-island",
    displayName: "Mid-Island",
    zoneType: "estate_area",
    aliases: ["mid island", "mid-island", "barren spot", "sion farm", "peter's rest"],
    estateNames: ["Barren Spot", "Sion Farm", "Peter's Rest"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
  zone({
    id: "stx_rainbow_beach",
    island: "stx",
    slug: "rainbow-beach",
    displayName: "Rainbow Beach",
    zoneType: "landmark",
    aliases: ["rainbow beach", "rainbow", "sprat hall"],
    estateNames: ["Sprat Hall", "Frederiksted"],
    source: stxSource,
    reviewStatus: "needs_review",
  }),
];