// Auto-generated by scripts/atlas/build-relationships.ts

export type AtlasRelationshipType =
  | "related_to"
  | "near"
  | "adjacent_to"
  | "appears_on"
  | "historic_map_reference";

export type AtlasRelationship = {
  id: string;
  fromId: string;
  fromName: string;
  toName: string;
  toId: string | null;
  type: AtlasRelationshipType;
  confidence: number;
  source: string;
  notes: string;
};

export const atlasRelationships = [
  {
    "id": "st_thomas_estate_dorothea_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_dorothea",
    "fromName": "Estate Dorothea",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Dorothea appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_neltjeberg_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_neltjeberg",
    "fromName": "Estate Neltjeberg",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Neltjeberg appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_hull_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_hull",
    "fromName": "Estate Hull",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Hull appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_st_peter_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_st_peter",
    "fromName": "Estate St. Peter",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate St. Peter appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_lovenlund_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_lovenlund",
    "fromName": "Estate Lovenlund",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Lovenlund appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_rosendal_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_rosendal",
    "fromName": "Estate Rosendal",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Rosendal appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_annas_retreat_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_annas_retreat",
    "fromName": "Estate Anna's Retreat",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Anna's Retreat appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_tutu_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_tutu",
    "fromName": "Estate Tutu",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Tutu appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_nazareth_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_nazareth",
    "fromName": "Estate Nazareth",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Nazareth appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_nazareth_related_to_nazareth_bay",
    "fromId": "st_thomas_estate_nazareth",
    "fromName": "Estate Nazareth",
    "toName": "Nazareth Bay",
    "toId": null,
    "type": "related_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Nazareth is linked to unverified related name Nazareth Bay."
  },
  {
    "id": "st_thomas_estate_nazareth_related_to_beverhout_point",
    "fromId": "st_thomas_estate_nazareth",
    "fromName": "Estate Nazareth",
    "toName": "Beverhout Point",
    "toId": null,
    "type": "adjacent_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Nazareth is linked to unverified related name Beverhout Point."
  },
  {
    "id": "st_thomas_estate_nazareth_related_to_bourgen_estate",
    "fromId": "st_thomas_estate_nazareth",
    "fromName": "Estate Nazareth",
    "toName": "Bourgen Estate",
    "toId": null,
    "type": "related_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Nazareth is linked to unverified related name Bourgen Estate."
  },
  {
    "id": "st_thomas_estate_frydendal_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_frydendal",
    "fromName": "Estate Frydendal",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Frydendal appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_bovoni_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_bovoni",
    "fromName": "Estate Bovoni",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bovoni appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_estate_bovoni_related_to_bovoni_bay",
    "fromId": "st_thomas_estate_bovoni",
    "fromName": "Estate Bovoni",
    "toName": "Bovoni Bay",
    "toId": null,
    "type": "related_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bovoni is linked to unverified related name Bovoni Bay."
  },
  {
    "id": "st_thomas_estate_bovoni_related_to_bovoni_cay",
    "fromId": "st_thomas_estate_bovoni",
    "fromName": "Estate Bovoni",
    "toName": "Bovoni Cay",
    "toId": null,
    "type": "related_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bovoni is linked to unverified related name Bovoni Cay."
  },
  {
    "id": "st_thomas_estate_bovoni_related_to_bovoni_estate",
    "fromId": "st_thomas_estate_bovoni",
    "fromName": "Estate Bovoni",
    "toName": "Bovoni Estate",
    "toId": "st_thomas_estate_bovoni",
    "type": "related_to",
    "confidence": 0.75,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bovoni is linked to Estate Bovoni."
  },
  {
    "id": "st_thomas_estate_bovoni_related_to_batzley_point",
    "fromId": "st_thomas_estate_bovoni",
    "fromName": "Estate Bovoni",
    "toName": "Batzley Point",
    "toId": null,
    "type": "adjacent_to",
    "confidence": 0.45,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bovoni is linked to unverified related name Batzley Point."
  },
  {
    "id": "st_thomas_estate_bolongo_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_estate_bolongo",
    "fromName": "Estate Bolongo",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Estate Bolongo appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_town_charlotte_amalie_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_town_charlotte_amalie",
    "fromName": "Charlotte Amalie",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Charlotte Amalie appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_bay_magens_bay_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_bay_magens_bay",
    "fromName": "Magens Bay",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Magens Bay appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_cay_hans_lollik_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_cay_hans_lollik",
    "fromName": "Hans Lollik",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Hans Lollik appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_cay_inner_brass_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_cay_inner_brass",
    "fromName": "Inner Brass",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Inner Brass appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_cay_outer_brass_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_cay_outer_brass",
    "fromName": "Outer Brass",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Outer Brass appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_cay_thatch_cay_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_cay_thatch_cay",
    "fromName": "Thatch Cay",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Thatch Cay appears on st_thomas_historic_map_early."
  },
  {
    "id": "st_thomas_cay_grass_cay_appears_on_st_thomas_historic_map_early",
    "fromId": "st_thomas_cay_grass_cay",
    "fromName": "Grass Cay",
    "toName": "st_thomas_historic_map_early",
    "toId": "st_thomas_historic_map_early",
    "type": "appears_on",
    "confidence": 0.8,
    "source": "st_thomas_historic_map_early",
    "notes": "Grass Cay appears on st_thomas_historic_map_early."
  }
] as const satisfies readonly AtlasRelationship[];
