// Auto-generated by scripts/build-atlas-starter.ts

export const gazetteerMetadata = {
  "generatedAt": "2026-07-02T00:51:22.268Z",
  "title": "VI Guide Starter Gazetteer",
  "sourceMapId": "st_thomas_historic_map_early",
  "totalFeatures": 19,
  "byIsland": {
    "st_thomas": 19
  },
  "byFeatureType": {
    "estate": 12,
    "town": 1,
    "bay": 1,
    "cay": 5
  }
} as const;
