// Auto-generated by scripts/build-atlas-starter.ts

export type IslandCode = "st_thomas" | "st_john" | "st_croix" | "water_island";

export type GazetteerFeature = {
  id: string;
  canonicalName: string;
  normalizedName: string;
  displayName: string;
  featureType: string;
  category: string;
  island: IslandCode;
  islandLabel: string;
  aliases: readonly string[];
  coordinates: { lat: number; lng: number } | null;
  sourceMaps: readonly string[];
  relatedNames: readonly string[];
  searchText: string;
  notes: string;
};

export const gazetteer = [
  {
    "id": "st_thomas_estate_dorothea",
    "canonicalName": "Dorothea",
    "normalizedName": "dorothea",
    "displayName": "Estate Dorothea",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Dorothea"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "dorothea estate dorothea estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_neltjeberg",
    "canonicalName": "Neltjeberg",
    "normalizedName": "neltjeberg",
    "displayName": "Estate Neltjeberg",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Neltjebjerg",
      "Estate Neltjeberg"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "neltjeberg neltjebjerg estate neltjeberg estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_hull",
    "canonicalName": "Hull",
    "normalizedName": "hull",
    "displayName": "Estate Hull",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Hull"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "hull estate hull estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_st_peter",
    "canonicalName": "St. Peter",
    "normalizedName": "st. peter",
    "displayName": "Estate St. Peter",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Saint Peter",
      "Estate St. Peter"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "st. peter saint peter estate st. peter estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_lovenlund",
    "canonicalName": "Lovenlund",
    "normalizedName": "lovenlund",
    "displayName": "Estate Lovenlund",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Løvenlund",
      "Estate Lovenlund"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "lovenlund løvenlund estate lovenlund estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_rosendal",
    "canonicalName": "Rosendal",
    "normalizedName": "rosendal",
    "displayName": "Estate Rosendal",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Rosendahl, Estate Rosendal",
      "Estate Rosendal"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "rosendal rosendahl, estate rosendal estate rosendal estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_annas_retreat",
    "canonicalName": "Anna's Retreat",
    "normalizedName": "annas retreat",
    "displayName": "Estate Anna's Retreat",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Annas Retreat",
      "Estate Anna's Retreat"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "anna's retreat annas retreat estate anna's retreat estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_tutu",
    "canonicalName": "Tutu",
    "normalizedName": "tutu",
    "displayName": "Estate Tutu",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Tutu"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "tutu estate tutu estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_nazareth",
    "canonicalName": "Nazareth",
    "normalizedName": "nazareth",
    "displayName": "Estate Nazareth",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Nazareth"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [
      "Nazareth Bay",
      "Beverhout Point",
      "Bourgen Estate"
    ],
    "searchText": "nazareth estate nazareth estate st_thomas nazareth bay beverhout point bourgen estate visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_frydendal",
    "canonicalName": "Frydendal",
    "normalizedName": "frydendal",
    "displayName": "Estate Frydendal",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Fryden Dal",
      "Estate Frydendal"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "frydendal fryden dal estate frydendal estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_bovoni",
    "canonicalName": "Bovoni",
    "normalizedName": "bovoni",
    "displayName": "Estate Bovoni",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Bovoni",
      "Bovoni Estate"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [
      "Bovoni Bay",
      "Bovoni Cay",
      "Bovoni Estate",
      "Batzley Point"
    ],
    "searchText": "bovoni estate bovoni bovoni estate estate st_thomas bovoni bay bovoni cay batzley point visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_estate_bolongo",
    "canonicalName": "Bolongo",
    "normalizedName": "bolongo",
    "displayName": "Estate Bolongo",
    "featureType": "estate",
    "category": "estate",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Estate Bolongo"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "bolongo estate bolongo estate st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_town_charlotte_amalie",
    "canonicalName": "Charlotte Amalie",
    "normalizedName": "charlotte amalie",
    "displayName": "Charlotte Amalie",
    "featureType": "town",
    "category": "town",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Charlotte Amalia",
      "Amalienborg"
    ],
    "coordinates": {
      "lat": 18.3419,
      "lng": -64.9307
    },
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "charlotte amalie charlotte amalia amalienborg town st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_bay_magens_bay",
    "canonicalName": "Magens Bay",
    "normalizedName": "magens bay",
    "displayName": "Magens Bay",
    "featureType": "bay",
    "category": "bay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Magen's Bay"
    ],
    "coordinates": {
      "lat": 18.3637,
      "lng": -64.9304
    },
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "magens bay magen's bay bay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_cay_hans_lollik",
    "canonicalName": "Hans Lollik",
    "normalizedName": "hans lollik",
    "displayName": "Hans Lollik",
    "featureType": "cay",
    "category": "cay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Hans Lollick",
      "Hans Lollik Island"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "hans lollik hans lollick hans lollik island cay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_cay_inner_brass",
    "canonicalName": "Inner Brass",
    "normalizedName": "inner brass",
    "displayName": "Inner Brass",
    "featureType": "cay",
    "category": "cay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Inner Brass Island"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "inner brass inner brass island cay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_cay_outer_brass",
    "canonicalName": "Outer Brass",
    "normalizedName": "outer brass",
    "displayName": "Outer Brass",
    "featureType": "cay",
    "category": "cay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Outer Brass Island"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "outer brass outer brass island cay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_cay_thatch_cay",
    "canonicalName": "Thatch Cay",
    "normalizedName": "thatch cay",
    "displayName": "Thatch Cay",
    "featureType": "cay",
    "category": "cay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [
      "Thatch Island"
    ],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "thatch cay thatch island cay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  },
  {
    "id": "st_thomas_cay_grass_cay",
    "canonicalName": "Grass Cay",
    "normalizedName": "grass cay",
    "displayName": "Grass Cay",
    "featureType": "cay",
    "category": "cay",
    "island": "st_thomas",
    "islandLabel": "St. Thomas",
    "aliases": [],
    "coordinates": null,
    "sourceMaps": [
      "st_thomas_historic_map_early"
    ],
    "relatedNames": [],
    "searchText": "grass cay cay st_thomas visible on uploaded historic st. thomas map.",
    "notes": "Visible on uploaded historic St. Thomas map."
  }
] as const;
