// Auto-generated by scripts/build-atlas-starter.ts
export const sourceMaps = [
  {
    "id": "st_thomas_historic_map_early",
    "title": "Historic Map of St. Thomas",
    "island": "st_thomas",
    "imagePath": "/images/maps/st-thomas-historic-map.jpeg",
    "status": "manual_transcription_started"
  }
] as const;
