// Auto-generated by scripts/build-atlas-starter.ts

export type SourceMap = {
  id: string;
  title: string;
  island: "st_thomas" | "st_john" | "st_croix" | "water_island";
  imagePath: string;
  status: "manual_transcription_started" | "draft" | "verified";
  notes?: string;
};

export const sourceMaps = [
  {
    "id": "st_thomas_historic_map_early",
    "title": "Historic Map of St. Thomas",
    "island": "st_thomas",
    "imagePath": "/images/maps/st-thomas-historic-map.jpeg",
    "status": "manual_transcription_started",
    "notes": "Starter transcription from uploaded historic St. Thomas map."
  }
] as const;
