import { ACCOMMODATIONS as BASE_ACCOMMODATIONS } from "./loader";
import type { AccommodationRecord } from "./types";

const VERIFIED_AT = "2026-08-23";
const STJ_FALLBACK = "/images/places/fallbacks/place-stj.svg";
const STX_FALLBACK = "/images/places/fallbacks/place-stx.svg";

/**
 * High-confidence operating accommodations that were missing from the restored
 * lodging catalog. Exact-location photos remain pending until individually
 * reviewed; generic island artwork prevents a misleading property-photo claim.
 */
export const RESTORED_ACCOMMODATIONS: AccommodationRecord[] = [
  {
    id: "the-saint-resort",
    slug: "the-saint-resort",
    name: "The Saint Resort",
    island: "stj",
    category: "resort",
    location: "Cruz Bay",
    description:
      "An adults-only resort, spa, restaurant, and day club near downtown Cruz Bay with suites, villas, pools, wellness amenities, and sunset views.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["adults only", "spa", "wellness", "cruz bay", "official site verified"],
    featured: true,
    phone: "888-524-4012",
    website: "https://www.saintstj.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://www.saintstj.com/",
    sourceUrls: [
      "https://www.saintstj.com/",
      "https://www.visitusvi.com/experience/top-st-john-luxury-resorts/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "the-westin-st-john-resort-villas",
    slug: "the-westin-st-john-resort-villas",
    name: "The Westin St. John Resort Villas",
    island: "stj",
    category: "resort",
    location: "Great Cruz Bay",
    description:
      "A beachfront vacation ownership resort on Great Cruz Bay with studios, townhouses and villas, a large pool, restaurants, fitness facilities, and family activities.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["beachfront", "family friendly", "villas", "pool", "great cruz bay"],
    featured: true,
    address: "300B Chocolate Hole, Great Cruz Bay, VI 00830",
    phone: "340-693-8000",
    website:
      "https://www.marriott.com/en-us/hotels/sttwj-the-westin-st-john-resort-villas/overview/",
    sourceLabel: "Official Marriott property website",
    sourceUrl:
      "https://www.marriott.com/en-us/hotels/sttwj-the-westin-st-john-resort-villas/overview/",
    sourceUrls: [
      "https://www.marriott.com/en-us/hotels/sttwj-the-westin-st-john-resort-villas/overview/",
      "https://www.visitusvi.com/experience/top-st-john-luxury-resorts/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "estate-lindholm",
    slug: "estate-lindholm",
    name: "Estate Lindholm",
    island: "stj",
    category: "guesthouse",
    location: "Estate Caneel Bay / Cruz Bay",
    description:
      "An intimate tropical inn set among restored Danish ruins on the hillside above Cruz Bay, adjacent to Virgin Islands National Park.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["historic", "inn", "cruz bay", "national park", "harbor view"],
    address: "6B Estate Caneel Bay, St. John, VI 00830",
    phone: "340-227-4724",
    website: "https://estatelindholm.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://estatelindholm.com/",
    sourceUrls: [
      "https://estatelindholm.com/",
      "https://www.visitusvi.com/listing/st-john/584/estate-lindholm/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "st-john-inn",
    slug: "st-john-inn",
    name: "St. John Inn",
    island: "stj",
    category: "hotel",
    location: "Cruz Bay",
    description:
      "A small boutique hotel in Cruz Bay with a pool, complimentary continental breakfast, beach gear, Wi-Fi, and walkable access to the ferry, dining, and shopping.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["boutique", "cruz bay", "pool", "breakfast included", "walkable"],
    address: "277 Contant & Enighed, Cruz Bay, St. John, VI 00831",
    phone: "340-693-8688",
    website: "https://stjohninn.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://stjohninn.com/",
    sourceUrls: ["https://stjohninn.com/"],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "sea-shore-allure",
    slug: "sea-shore-allure",
    name: "Sea Shore Allure",
    island: "stj",
    category: "resort",
    location: "Cruz Bay / Enighed",
    description:
      "A small waterfront St. John property with one- to three-bedroom suites, private balconies, kitchens, pool access, and close proximity to Cruz Bay.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["waterfront", "suites", "pool", "cruz bay", "kitchen"],
    address: "271 Enighed Ln, Cruz Bay, St. John, VI 00830",
    phone: "340-779-2800",
    website: "https://seashoreallure.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://seashoreallure.com/",
    sourceUrls: [
      "https://seashoreallure.com/",
      "https://www.visitusvi.com/listing/st-john/605/sea-shore-allure/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "cruz-bay-boutique-hotel",
    slug: "cruz-bay-boutique-hotel",
    name: "Cruz Bay Boutique Hotel",
    island: "stj",
    category: "hotel",
    location: "Cruz Bay",
    description:
      "An intimate boutique hotel in the heart of Cruz Bay with guest rooms and a penthouse apartment, positioned for walkable access to restaurants, bars, shopping, and ferry connections.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["boutique", "cruz bay", "walkable", "downtown", "ferry access"],
    website: "https://hotelcruzbay.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://hotelcruzbay.com/hotel.html",
    sourceUrls: ["https://hotelcruzbay.com/hotel.html"],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "concordia-eco-resort",
    slug: "concordia-eco-resort",
    name: "Concordia Eco Resort",
    island: "stj",
    category: "resort",
    location: "Concordia / Coral Bay",
    description:
      "An eco-focused St. John resort near Salt Pond Bay offering environmentally minded villas and rustic ridge-line accommodations in the island's quieter southeast.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["eco resort", "coral bay", "salt pond", "nature", "quiet"],
    address: "20 Concordia, St. John, VI 00830",
    phone: "304-301-6472",
    website: "https://concordiaecoresort.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://concordiaecoresort.com/",
    sourceUrls: ["https://concordiaecoresort.com/"],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "cinnamon-bay-beach-campground",
    slug: "cinnamon-bay-beach-campground",
    name: "Cinnamon Bay Beach & Campground",
    island: "stj",
    category: "campground",
    location: "Cinnamon Bay / Virgin Islands National Park",
    description:
      "The designated campground inside Virgin Islands National Park, offering bare sites, eco-tents and cottages with direct access to Cinnamon Bay Beach and on-site visitor services.",
    heroImage: STJ_FALLBACK,
    imageStatus: "pending",
    tags: ["campground", "national park", "beachfront", "eco tents", "cottages"],
    phone: "340-714-7144",
    website: "https://www.cinnamonbayvi.com/",
    sourceLabel: "Official campground website; National Park Service cross-check",
    sourceUrl: "https://www.cinnamonbayvi.com/",
    sourceUrls: [
      "https://www.cinnamonbayvi.com/",
      "https://www.nps.gov/viis/planyourvisit/camping.htm",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "grapetree-bay-hotel-villas",
    slug: "grapetree-bay-hotel-villas",
    name: "Grapetree Bay Hotel & Villas",
    island: "stx",
    category: "hotel",
    location: "Grapetree Bay / East End",
    description:
      "A restored oceanfront East End hotel with ocean-facing rooms and seaside villas, a freshwater pool, dining, and direct access to a quieter St. Croix coastal setting.",
    heroImage: STX_FALLBACK,
    imageStatus: "pending",
    tags: ["oceanfront", "east end", "villas", "pool", "boutique"],
    address: "5000 S Grapetree Bay Road, Christiansted, VI 00820",
    phone: "340-249-0700",
    website: "https://grapetreebayhotel.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://grapetreebayhotel.com/",
    sourceUrls: [
      "https://grapetreebayhotel.com/",
      "https://www.visitusvi.com/experience/st-croix-beachfront-hotels/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
  {
    id: "the-waves-cane-bay",
    slug: "the-waves-cane-bay",
    name: "The Waves Cane Bay",
    island: "stx",
    category: "hotel",
    location: "Cane Bay / North Shore",
    description:
      "An intimate oceanfront boutique hotel at Cane Bay with private-patio suites, some kitchenettes, on-site dining and bars, and quick access to Cane Bay Beach.",
    heroImage: STX_FALLBACK,
    imageStatus: "pending",
    tags: ["oceanfront", "cane bay", "boutique", "north shore", "dining"],
    address: "112C Cane Bay, St. Croix, VI 00851",
    phone: "340-514-2261",
    website: "https://www.thewavescanebay.com/",
    sourceLabel: "Official property website",
    sourceUrl: "https://www.thewavescanebay.com/",
    sourceUrls: [
      "https://www.thewavescanebay.com/",
      "https://www.visitusvi.com/experience/st-croix-beachfront-hotels/",
    ],
    verificationStatus: "official-site-verified",
    verifiedAt: VERIFIED_AT,
  },
];

const baseSlugs = new Set(BASE_ACCOMMODATIONS.map((item) => item.slug));

export const ACCOMMODATIONS: AccommodationRecord[] = [
  ...BASE_ACCOMMODATIONS,
  ...RESTORED_ACCOMMODATIONS.filter((item) => !baseSlugs.has(item.slug)),
].sort((a, b) => a.name.localeCompare(b.name));
