// Auto-generated by scripts/extract-sixto-estate-history.ts.
// Curated short excerpts from Adolph Sixto, Time and I; or, Looking Forward.
// Keep excerpts short and cite source/page in the UI.

export type SixtoEstateExtract = {
  estateId: string;
  estateName: string;
  baseName: string;
  island: string;
  quarter: string;
  sourceId: string;
  sourceTitle: string;
  author: string;
  year: number;
  pages: number[];
  excerpts: string[];
  matchCount: number;
  researchStatus: "sixto-excerpt-found" | "no-sixto-excerpt-found";
};

export const sixtoEstateExtracts = [
  {
    "estateId": "st_thomas-estate-cane",
    "estateName": "Estate cane",
    "baseName": "cane",
    "island": "st_thomas",
    "quarter": "",
    "sourceId": "source:sixto-time-and-i-1902",
    "sourceTitle": "Time and I; or, Looking Forward",
    "author": "Adolph Sixto",
    "year": 1902,
    "pages": [],
    "excerpts": [
      "P r o te c tio n.—Cane, th e sta p ie p ro d u ct.—C o-operation",
      "of cane to one to n of su g a r.—M anufacturing c o s t of one",
      "su g a r beet and su gar cane.—L ab ou r sa v in g m achines.—"
    ],
    "matchCount": 3,
    "researchStatus": "sixto-excerpt-found"
  },
  {
    "estateId": "st_croix-estate-cane",
    "estateName": "Estate CANE",
    "baseName": "CANE",
    "island": "st_croix",
    "quarter": "",
    "sourceId": "source:sixto-time-and-i-1902",
    "sourceTitle": "Time and I; or, Looking Forward",
    "author": "Adolph Sixto",
    "year": 1902,
    "pages": [],
    "excerpts": [
      "P r o te c tio n.—Cane, th e sta p ie p ro d u ct.—C o-operation",
      "of cane to one to n of su g a r.—M anufacturing c o s t of one",
      "su g a r beet and su gar cane.—L ab ou r sa v in g m achines.—"
    ],
    "matchCount": 3,
    "researchStatus": "sixto-excerpt-found"
  },
  {
    "estateId": "st_thomas-estate-island",
    "estateName": "Estate Island",
    "baseName": "Island",
    "island": "st_thomas",
    "quarter": "",
    "sourceId": "source:sixto-time-and-i-1902",
    "sourceTitle": "Time and I; or, Looking Forward",
    "author": "Adolph Sixto",
    "year": 1902,
    "pages": [],
    "excerpts": [
      "th e Island. It m ade its appearanee in a \" d in n itv hall ”",
      "supposed to be inform ed on m o st thing-g, th a t th e Island"
    ],
    "matchCount": 2,
    "researchStatus": "sixto-excerpt-found"
  },
  {
    "estateId": "st_croix-estate-h-o-p",
    "estateName": "Estate H o p",
    "baseName": "H o p",
    "island": "st_croix",
    "quarter": "",
    "sourceId": "source:sixto-time-and-i-1902",
    "sourceTitle": "Time and I; or, Looking Forward",
    "author": "Adolph Sixto",
    "year": 1902,
    "pages": [],
    "excerpts": [
      "t H o p e...........................................................115"
    ],
    "matchCount": 1,
    "researchStatus": "sixto-excerpt-found"
  },
  {
    "estateId": "st_thomas-estate-road",
    "estateName": "Estate Road",
    "baseName": "Road",
    "island": "st_thomas",
    "quarter": "",
    "sourceId": "source:sixto-time-and-i-1902",
    "sourceTitle": "Time and I; or, Looking Forward",
    "author": "Adolph Sixto",
    "year": 1902,
    "pages": [],
    "excerpts": [
      "D ia g o n a l and Black B road Cloth of h est m anufacturers"
    ],
    "matchCount": 1,
    "researchStatus": "sixto-excerpt-found"
  }
] as SixtoEstateExtract[];

export const sixtoEstateExtractsByEstateName = Object.fromEntries(
  sixtoEstateExtracts.map((item) => [
    item.baseName
      .toLowerCase()
      .replace(/^estate\\s+/i, "")
      .replace(/['’]/g, "")
      .replace(/&/g, "and")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, ""),
    item,
  ]),
) as Record<string, SixtoEstateExtract>;

export function getSixtoEstateExtract(name: unknown) {
  const key = String(name ?? "")
    .trim()
    .replace(/^Estate\\s+/i, "")
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return sixtoEstateExtractsByEstateName[key] ?? null;
}
