import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { gazetteer } from "../../src/data/atlas/gazetteer";

type RelationshipType =
  | "related_to"
  | "near"
  | "adjacent_to"
  | "appears_on"
  | "historic_map_reference";

type AtlasRelationship = {
  id: string;
  fromId: string;
  fromName: string;
  toName: string;
  toId: string | null;
  type: RelationshipType;
  confidence: number;
  source: string;
  notes: string;
};

function normalize(value: unknown) {
  return String(value ?? "")
    .replace(/^Estate\s+/i, "")
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function slug(value: string) {
  return normalize(value).replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function findByName(name: string) {
  const target = normalize(name);

  return gazetteer.find((item) => {
    const aliases = item.aliases || [];
    return [
      item.canonicalName,
      item.displayName,
      item.normalizedName,
      ...aliases,
    ].some((value) => normalize(value) === target);
  });
}

const relationships: AtlasRelationship[] = [];

for (const item of gazetteer) {
  for (const sourceMapId of item.sourceMaps) {
    relationships.push({
      id: `${item.id}_appears_on_${sourceMapId}`,
      fromId: item.id,
      fromName: item.displayName,
      toName: sourceMapId,
      toId: sourceMapId,
      type: "appears_on",
      confidence: 0.8,
      source: sourceMapId,
      notes: `${item.displayName} appears on ${sourceMapId}.`,
    });
  }

  for (const relatedName of item.relatedNames) {
    const related = findByName(relatedName);

    relationships.push({
      id: `${item.id}_related_to_${slug(relatedName)}`,
      fromId: item.id,
      fromName: item.displayName,
      toName: relatedName,
      toId: related?.id ?? null,
      type:
        relatedName.toLowerCase().includes("point") ? "adjacent_to" : "related_to",
      confidence: related ? 0.75 : 0.45,
      source: item.sourceMaps[0] || "manual_gazetteer",
      notes: related
        ? `${item.displayName} is linked to ${related.displayName}.`
        : `${item.displayName} is linked to unverified related name ${relatedName}.`,
    });
  }
}

mkdirSync("data/atlas/generated", { recursive: true });
writeFileSync(
  "data/atlas/generated/atlas-relationships.json",
  `${JSON.stringify(relationships, null, 2)}\n`,
);

mkdirSync(dirname("src/data/atlas/atlasRelationships.ts"), { recursive: true });
writeFileSync(
  "src/data/atlas/atlasRelationships.ts",
  `// Auto-generated by scripts/atlas/build-relationships.ts

export type AtlasRelationshipType =
  | "related_to"
  | "near"
  | "adjacent_to"
  | "appears_on"
  | "historic_map_reference";

export type AtlasRelationship = {
  id: string;
  fromId: string;
  fromName: string;
  toName: string;
  toId: string | null;
  type: AtlasRelationshipType;
  confidence: number;
  source: string;
  notes: string;
};

export const atlasRelationships = ${JSON.stringify(
    relationships,
    null,
    2,
  )} as const satisfies readonly AtlasRelationship[];
`,
);

console.log("Atlas relationships built.");
console.log({
  relationships: relationships.length,
  unresolved: relationships.filter((item) => !item.toId && item.type !== "appears_on").length,
});
