import {
  ACTIVITY_CATEGORY_LABELS as BASE_ACTIVITY_CATEGORY_LABELS,
  ACTIVITY_COVERAGE_SOURCES as BASE_ACTIVITY_COVERAGE_SOURCES,
  BOOKABLE_EXPERIENCES as BASE_BOOKABLE_EXPERIENCES,
  ISLAND_NAMES as BASE_ISLAND_NAMES,
} from "./bookable-experiences";
import type {
  ActivityCategory as BaseActivityCategory,
  BookableExperience as BaseBookableExperience,
} from "./bookable-experiences";

export type ActivityCategory = BaseActivityCategory | "atv" | "land-tour";

export type BookableExperience = Omit<BaseBookableExperience, "category"> & {
  category: ActivityCategory;
};

const RESTORED_BOOKABLE_EXPERIENCES: BookableExperience[] = [
  // St. Croix — current Visit USVI excursion-guide gaps.
  {
    id: "stx-sea-thru-bio-bay",
    name: "Bioluminescent Bay Clear-Kayak Tour",
    operator: "Sea Thru Kayaks VI",
    category: "kayak",
    kind: "tour",
    island: "stx",
    location: "Salt River Bay, St. Croix",
    duration: "About 2 hours",
    summary:
      "A guided nighttime paddle from Salt River Marina into the bioluminescent bay, with transparent-kayak options and interpretation of the protected ecosystem.",
    highlights: ["Bioluminescence", "Clear kayak", "Salt River Bay", "Guided"],
    sourceUrl: "https://seathrukayaksvi.com/bioluminescent-bay-kayak-tour/",
    sourceLabel: "Sea Thru Kayaks VI official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-parasail-virgin-islands",
    name: "Christiansted Parasailing",
    operator: "Parasail Virgin Islands",
    category: "parasailing",
    kind: "experience",
    island: "stx",
    location: "Christiansted Boardwalk, St. Croix",
    duration: "About 1 hour",
    summary:
      "A boat-based parasailing experience departing from Christiansted with tandem and triple-flight options offered by the operator.",
    highlights: ["Parasailing", "Christiansted", "Tandem flights", "Aerial views"],
    sourceUrl: "https://parasailvirginislands.com/rates-locations/",
    sourceLabel: "Parasail Virgin Islands official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-crucian-adventure-divers",
    name: "Frederiksted Guided Scuba Dive",
    operator: "Crucian Adventure Divers",
    category: "scuba",
    kind: "tour",
    island: "stx",
    location: "Frederiksted, St. Croix",
    duration: "Varies",
    summary:
      "Small-group guided scuba diving and instruction from Frederiksted, including shore, night, and introductory dive options.",
    highlights: ["Scuba", "Frederiksted Pier", "Small groups", "PADI instruction"],
    sourceUrl: "https://www.crucianadventuredivers.com/instruction",
    sourceLabel: "Crucian Adventure Divers official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "request-only",
  },
  {
    id: "stx-captain-cook-sportfishing",
    name: "St. Croix Sportfishing Charter",
    operator: "Captain Cook Charters",
    category: "fishing",
    kind: "tour",
    island: "stx",
    location: "St. Croix",
    duration: "4–10 hours",
    summary:
      "Private offshore sportfishing plus sunset and adventure-charter options aboard a dedicated St. Croix charter vessel.",
    highlights: ["Sportfishing", "Offshore", "Private charter", "Adventure trips"],
    sourceUrl: "https://captaincookchartersvi.com/",
    sourceLabel: "Captain Cook Charters official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-geckos-original-atv",
    name: "Gecko's Original ATV Tour",
    operator: "Gecko's Island Adventures",
    category: "atv",
    kind: "tour",
    island: "stx",
    location: "Frederiksted and St. Croix West End",
    duration: "About 2 hours",
    summary:
      "A guided ATV route through West End coastline, rainforest, mountaintop viewpoints, and historic plantation ruins.",
    highlights: ["ATV", "Rainforest", "Historic ruins", "West End"],
    sourceUrl: "https://www.geckosislandadventures.com/original-geckos-tour-most-popular/",
    sourceLabel: "Gecko's Island Adventures official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-carambola-zip-line",
    name: "Carambola Zip Line Adventure",
    operator: "Carambola Zip Line",
    category: "zipline",
    kind: "tour",
    island: "stx",
    location: "Estate River / Carambola Valley, St. Croix",
    duration: "Varies",
    summary:
      "A rainforest canopy adventure beginning with a safari ride to the ridge and continuing across three ziplines over Carambola Valley.",
    highlights: ["Zipline", "Rainforest", "Carambola Valley", "Safari transfer"],
    sourceUrl: "https://www.carambolazipline.com/",
    sourceLabel: "Carambola Zip Line official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-chant-frederiksted-walk",
    name: "Frederiksted Heritage Walking Tour",
    operator: "Crucian Heritage & Nature Tourism (CHANT)",
    category: "cultural",
    kind: "tour",
    island: "stx",
    location: "Frederiksted, St. Croix",
    duration: "About 2.5 hours",
    summary:
      "A guided walking tour interpreting Frederiksted's architecture, Emancipation history, Fort Frederik, and historic town streets.",
    highlights: ["Heritage", "Walking tour", "Emancipation history", "Frederiksted"],
    sourceUrl: "https://chantvi.org/",
    sourceLabel: "CHANT official website and Visit USVI current guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "request-only",
  },

  // St. John — current Visit USVI tours-and-excursions guide gaps.
  {
    id: "stj-seas-the-day-private-charter",
    name: "Private St. John Boat Charter",
    operator: "Seas the Day Charters & Tours",
    category: "boat-charter",
    kind: "tour",
    island: "stj",
    location: "St. John",
    duration: "Half or full day",
    summary:
      "A customizable private powerboat or catamaran day for snorkeling, beach hopping, and island cruising around St. John.",
    highlights: ["Private charter", "Snorkeling", "Beach hopping", "Custom route"],
    sourceUrl: "https://www.seasthedayusvi.com/",
    sourceLabel: "Operator official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-island-roots-private-charter",
    name: "Private St. John Island Charter",
    operator: "Island Roots Charters",
    category: "boat-charter",
    kind: "tour",
    island: "stj",
    location: "Cruz Bay, St. John",
    duration: "Half or full day",
    summary:
      "Private power-catamaran itineraries led by local captains to reefs, beaches, cays, and island stops around St. John.",
    highlights: ["Private charter", "Local captains", "Snorkeling", "Cruz Bay"],
    sourceUrl: "https://www.islandrootscharters.com/",
    sourceLabel: "Island Roots Charters official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-on-the-sea-charter",
    name: "St. John Catamaran Charter",
    operator: "On the Sea Charters",
    category: "boat-charter",
    kind: "tour",
    island: "stj",
    location: "Cruz Bay, St. John",
    duration: "Half or full day",
    summary:
      "Private catamaran trips for snorkeling, island hopping, beaches, and custom Virgin Islands itineraries from Cruz Bay.",
    highlights: ["Catamaran", "Private charter", "Sea turtles", "Island hopping"],
    sourceUrl: "https://ontheseacharters.com/",
    sourceLabel: "On the Sea Charters official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-explore-stj-jeep",
    name: "Private St. John Jeep Tour",
    operator: "Explore STJ",
    category: "land-tour",
    kind: "tour",
    island: "stj",
    location: "St. John",
    duration: "Half or full day",
    summary:
      "A private customizable Jeep tour combining beaches, light hiking, plantation ruins, viewpoints, and optional snorkeling stops.",
    highlights: ["Jeep tour", "Private", "Beaches", "Historic ruins"],
    sourceUrl: "https://www.visitusvi.com/experience/st-john-tours/",
    sourceLabel: "Visit USVI current St. John Tours & Excursions guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "request-only",
  },
  {
    id: "stj-ocean-surfari-jeep",
    name: "St. John Jeep Surfari",
    operator: "Ocean Surfari",
    category: "land-tour",
    kind: "tour",
    island: "stj",
    location: "St. John",
    duration: "Full day",
    summary:
      "A guided 4x4 island day built around beaches, rainforest, snorkeling, historical ruins, and off-the-beaten-path stops.",
    highlights: ["4x4", "Snorkeling", "Rainforest", "Custom tour"],
    sourceUrl: "https://oceansurfari.com/",
    sourceLabel: "Ocean Surfari official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-star-fish-island-tour",
    name: "Private St. John Island Tour",
    operator: "Star Fish Tours & Taxi",
    category: "land-tour",
    kind: "tour",
    island: "stj",
    location: "St. John",
    duration: "Custom",
    summary:
      "A private open-air island tour led by St. Johnian guides with customizable beach, overlook, plantation-ruin, and history stops.",
    highlights: ["Local guide", "Open-air safari", "History", "Custom route"],
    sourceUrl: "https://www.visitusvi.com/experience/st-john-tours/",
    sourceLabel: "Visit USVI current St. John Tours & Excursions guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "request-only",
  },
  {
    id: "stj-cruz-bay-jet-ski",
    name: "Pillsbury Sound Jet Ski Tour",
    operator: "Cruz Bay Watersports",
    category: "jet-ski",
    kind: "tour",
    island: "stj",
    location: "Pillsbury Sound, St. John",
    duration: "Varies",
    summary:
      "A guided WaveRunner tour exploring Pillsbury Sound and nearby waters from St. John.",
    highlights: ["Jet ski", "Guided", "Pillsbury Sound", "Watersports"],
    sourceUrl: "https://cruzbaywatersports.com/st-john-excursions/",
    sourceLabel: "Cruz Bay Watersports official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-haunt-historic-ghost-tour",
    name: "Historic Ghost Tour Cruz Bay",
    operator: "Haunt Historic Ghost Tours",
    category: "cultural",
    kind: "tour",
    island: "stj",
    location: "Cruz Bay, St. John",
    duration: "About 2 hours",
    summary:
      "An evening walking tour through Cruz Bay centered on local history, island legends, and reported haunted sites.",
    highlights: ["Walking tour", "Cruz Bay", "Island legends", "Evening"],
    sourceUrl: "https://www.vighosttours.com/",
    sourceLabel: "Operator official website and Visit USVI current St. John guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "request-only",
  },

  // St. Thomas — current Visit USVI snorkeling and must-do guide gaps.
  {
    id: "stt-funtime-jet-ski",
    name: "Lindbergh Bay Jet Ski Tour",
    operator: "Funtime Jet Ski Rentals & Boat Charters",
    category: "jet-ski",
    kind: "experience",
    island: "stt",
    location: "Lindbergh Bay Beach, St. Thomas",
    duration: "30–60 minutes",
    summary:
      "Jet-ski rentals and guided one-hour rides from Lindbergh Bay, with operator instruction before departure.",
    highlights: ["Jet ski", "Lindbergh Bay", "Guided option", "Watersports"],
    sourceUrl: "https://www.funtimejetskivi.com/",
    sourceLabel: "Funtime official website and Visit USVI current must-do guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-st-thomas-snorkeling-tour",
    name: "St. Thomas Reef Snorkeling Tour",
    operator: "St. Thomas Snorkeling",
    category: "snorkeling",
    kind: "tour",
    island: "stt",
    location: "St. Thomas East End and surrounding bays",
    duration: "3.5–4 hours",
    summary:
      "Shared and private small-group snorkeling trips to turtle, reef, and offshore sites around St. Thomas.",
    highlights: ["Snorkeling", "Small group", "Reefs", "Turtles"],
    sourceUrl: "https://stthomassnorkelingtours.com/",
    sourceLabel: "Operator official website and Visit USVI current snorkeling guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-scuba-snorkel-adventures",
    name: "Private St. Thomas Snorkel Adventure",
    operator: "St. Thomas Scuba & Snorkel Adventures",
    category: "snorkeling",
    kind: "tour",
    island: "stt",
    location: "Hull Bay and St. Thomas",
    duration: "Custom",
    summary:
      "Private eco-guided snorkeling and mixed island adventures built around secluded reefs, turtles, wildlife, and guest comfort.",
    highlights: ["Private tour", "Snorkeling", "Eco guide", "Custom itinerary"],
    sourceUrl: "https://www.stthomasadventures.com/",
    sourceLabel: "Operator official website and Visit USVI current snorkeling guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-ocean-surfari-snorkel",
    name: "St. Thomas Reef Surfari",
    operator: "Ocean Surfari",
    category: "snorkeling",
    kind: "tour",
    island: "stt",
    location: "Red Hook, St. Thomas",
    duration: "Half or full day",
    summary:
      "Catamaran snorkeling trips from Red Hook to reef habitats around St. Thomas and the St. James cays.",
    highlights: ["Catamaran", "Snorkeling", "Red Hook", "Reef ecology"],
    sourceUrl: "https://oceansurfari.com/",
    sourceLabel: "Ocean Surfari official website and Visit USVI current snorkeling guide",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-sonic-private-snorkel-charter",
    name: "Private St. Thomas Snorkel Charter",
    operator: "Sonic Charters",
    category: "boat-charter",
    kind: "tour",
    island: "stt",
    location: "St. Thomas",
    duration: "Custom day charter",
    summary:
      "A private powerboat charter with captain-guided snorkeling and island stops selected around sea conditions and group interests.",
    highlights: ["Private charter", "Snorkeling", "Custom route", "Family groups"],
    sourceUrl: "https://www.sonicchartersstthomas.com/",
    sourceLabel: "Visit USVI Preferred Partner listing and operator official website",
    verifiedAt: "2026-08-23",
    availabilityStatus: "operator-listed",
  },
];

export const BOOKABLE_EXPERIENCES: BookableExperience[] = [
  ...BASE_BOOKABLE_EXPERIENCES,
  ...RESTORED_BOOKABLE_EXPERIENCES,
];

export const ACTIVITY_CATEGORY_LABELS: Record<ActivityCategory, string> = {
  ...BASE_ACTIVITY_CATEGORY_LABELS,
  atv: "ATV & off-road",
  "land-tour": "Island & land tours",
};

export const ACTIVITY_COVERAGE_SOURCES = [
  ...BASE_ACTIVITY_COVERAGE_SOURCES,
  {
    id: "visit-usvi-st-croix-excursions",
    label: "Visit USVI St. Croix Excursions",
    url: "https://www.visitusvi.com/experience/st-croix-excursions-for-every-traveler/",
    scope: "Current named St. Croix excursion operators across water, land, heritage, and adventure categories",
  },
  {
    id: "visit-usvi-st-john-tours",
    label: "Visit USVI St. John Tours & Excursions",
    url: "https://www.visitusvi.com/experience/st-john-tours/",
    scope: "Current named St. John boat, land, eco, and specialty tour operators",
  },
  {
    id: "visit-usvi-st-thomas-snorkeling",
    label: "Visit USVI Best Snorkeling on St. Thomas",
    url: "https://www.visitusvi.com/experience/best-snorkeling-on-st-thomas/",
    scope: "Current named St. Thomas guided snorkeling operators",
  },
] as const;

export const ISLAND_NAMES = BASE_ISLAND_NAMES;

export const CURRENT_DESTINATION_ACTIVITY_OPERATORS = [
  "Sea Thru Kayaks VI",
  "Parasail Virgin Islands",
  "Crucian Adventure Divers",
  "Captain Cook Charters",
  "Gecko's Island Adventures",
  "Carambola Zip Line",
  "Crucian Heritage & Nature Tourism (CHANT)",
  "Seas the Day Charters & Tours",
  "Island Roots Charters",
  "On the Sea Charters",
  "Explore STJ",
  "Ocean Surfari",
  "Star Fish Tours & Taxi",
  "Haunt Historic Ghost Tours",
  "Funtime Jet Ski Rentals & Boat Charters",
  "St. Thomas Snorkeling",
  "St. Thomas Scuba & Snorkel Adventures",
  "Sonic Charters",
] as const;

export function getActivityCoverage() {
  return (["stt", "stj", "stx"] as const).map((island) => {
    const items = BOOKABLE_EXPERIENCES.filter((item) => item.island === island);
    return {
      island,
      count: items.length,
      operators: new Set(items.map((item) => item.operator)).size,
      categories: new Set(items.map((item) => item.category)).size,
    };
  });
}
