import type { CommerceBookingKind } from "@/types/commerce-booking";
import type { IntelligenceIsland } from "@/types/intelligence";

export type ActivityCategory =
  | "boat-charter"
  | "snorkeling"
  | "scuba"
  | "kayak"
  | "hiking"
  | "wildlife"
  | "zipline"
  | "parasailing"
  | "sailing"
  | "cultural";

export type BookableExperience = {
  id: string;
  name: string;
  operator: string;
  category: ActivityCategory;
  kind: Exclude<CommerceBookingKind, "accommodation">;
  island: IntelligenceIsland;
  location: string;
  duration: string;
  summary: string;
  highlights: string[];
  sourceUrl: string;
  sourceLabel: string;
  verifiedAt: string;
  availabilityStatus: "operator-listed" | "seasonal" | "request-only";
};

export const BOOKABLE_EXPERIENCES: BookableExperience[] = [
  {
    id: "stt-coral-world-sea-trek",
    name: "Sea Trek",
    operator: "Coral World Ocean Park",
    category: "wildlife",
    kind: "experience",
    island: "stt",
    location: "Coki Point, St. Thomas",
    duration: "About 1 hour",
    summary: "A guided helmet-dive walk on the ocean floor with admission to Coral World included.",
    highlights: ["Marine life", "Guided", "Ages 7+", "Park admission"],
    sourceUrl: "https://coralworldvi.com/activities/sea-trek/",
    sourceLabel: "Coral World official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-coral-world-snuba",
    name: "SNUBA Diving",
    operator: "Coral World Ocean Park",
    category: "scuba",
    kind: "experience",
    island: "stt",
    location: "Coki Point, St. Thomas",
    duration: "About 50 minutes",
    summary: "A guided SNUBA experience that combines snorkeling simplicity with underwater reef exploration.",
    highlights: ["SNUBA", "Reef", "Guided", "Equipment"],
    sourceUrl: "https://coralworldvi.com/",
    sourceLabel: "Coral World official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-vieco-cas-cay",
    name: "Cas Cay Kayak, Hike & Snorkel",
    operator: "Virgin Islands Ecotours",
    category: "kayak",
    kind: "tour",
    island: "stt",
    location: "Mangrove Lagoon, St. Thomas",
    duration: "3–5 hours",
    summary: "Guided paddling through the Mangrove Lagoon with hiking and snorkeling around Cas Cay.",
    highlights: ["Kayak", "Mangroves", "Hike", "Snorkel"],
    sourceUrl: "https://www.viecotours.com/st-thomas-virgin-islands",
    sourceLabel: "Virgin Islands Ecotours official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-tree-limin-zipline",
    name: "St. Thomas Zipline Tour",
    operator: "Tree Limin' Extreme",
    category: "zipline",
    kind: "tour",
    island: "stt",
    location: "St. Peter Mountain, St. Thomas",
    duration: "About 2.5 hours",
    summary: "A mountaintop zipline course with aerial island views and guided safety instruction.",
    highlights: ["Zipline", "Scenic views", "Guided", "Adventure"],
    sourceUrl: "https://ziplinestthomas.com/",
    sourceLabel: "Tree Limin' Extreme official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-seas-the-day-charter",
    name: "Private St. Thomas & St. John Charter",
    operator: "Seas the Day Charters USVI",
    category: "boat-charter",
    kind: "tour",
    island: "stt",
    location: "St. Thomas",
    duration: "Half or full day",
    summary: "Private powerboat itineraries for snorkeling, beaches, cays, and neighboring island stops.",
    highlights: ["Private charter", "Snorkeling", "Beaches", "Custom route"],
    sourceUrl: "https://www.seasthedayusvi.com/",
    sourceLabel: "Operator official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stt-island-adventures-snorkel",
    name: "Sea Turtle & Reef Snorkel",
    operator: "Island Adventures",
    category: "snorkeling",
    kind: "tour",
    island: "stt",
    location: "Sapphire Beach and Margaritaville departures",
    duration: "Varies by trip",
    summary: "Boat snorkeling excursions focused on sea turtles, coral reefs, and family-friendly water time.",
    highlights: ["Sea turtles", "Reef", "Boat tour", "Family"],
    sourceUrl: "https://funboatday.com/",
    sourceLabel: "Island Adventures official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-vieco-north-shore",
    name: "North Shore Kayak & Snorkel",
    operator: "Virgin Islands Ecotours",
    category: "kayak",
    kind: "tour",
    island: "stj",
    location: "St. John North Shore",
    duration: "Half day",
    summary: "A guided kayak and snorkel route along protected St. John shoreline and neighboring cays.",
    highlights: ["Kayak", "National Park", "Snorkel", "Guide"],
    sourceUrl: "https://www.viecotours.com/st-john/st-john-virgin-islands-excursions",
    sourceLabel: "Virgin Islands Ecotours official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-low-key-two-tank",
    name: "Two-Tank Morning Dive",
    operator: "Low Key Watersports",
    category: "scuba",
    kind: "tour",
    island: "stj",
    location: "Cruz Bay, St. John",
    duration: "About 3 hours",
    summary: "A two-tank guided dive trip for certified divers exploring reefs around St. John.",
    highlights: ["Scuba", "Two tanks", "Certified divers", "Boat dive"],
    sourceUrl: "https://divelowkey.com/",
    sourceLabel: "Low Key Watersports official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-cruz-bay-lime-out",
    name: "Lime Out Snorkel Sail",
    operator: "Cruz Bay Watersports",
    category: "sailing",
    kind: "tour",
    island: "stj",
    location: "Westin St. John departure",
    duration: "Half day",
    summary: "A catamaran snorkel sail along St. John's south shore with a stop at the floating taco bar.",
    highlights: ["Sailing", "Snorkeling", "Lunch stop", "Catamaran"],
    sourceUrl: "https://cruzbaywatersports.com/st-john-excursions/",
    sourceLabel: "Cruz Bay Watersports official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-cruz-bay-sunset",
    name: "Days End Sunset Sail",
    operator: "Cruz Bay Watersports",
    category: "sailing",
    kind: "experience",
    island: "stj",
    location: "Cruz Bay, St. John",
    duration: "About 1.5 hours",
    summary: "An evening catamaran sail through Pillsbury Sound timed around sunset.",
    highlights: ["Sunset", "Catamaran", "Evening", "Open water"],
    sourceUrl: "https://cruzbaywatersports.com/st-john-excursions/",
    sourceLabel: "Cruz Bay Watersports official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stj-arawak-kayak",
    name: "St. John Sea Kayak & Snorkel",
    operator: "Arawak Expeditions",
    category: "kayak",
    kind: "tour",
    island: "stj",
    location: "St. John shoreline and cays",
    duration: "Half or full day",
    summary: "Guided sea kayaking and snorkeling with instruction suitable for first-time paddlers.",
    highlights: ["Sea kayak", "Snorkel", "Instruction", "Small groups"],
    sourceUrl: "https://arawakexp.com/",
    sourceLabel: "Arawak Expeditions official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-big-beards-buck-island",
    name: "Buck Island Snorkel Tour",
    operator: "Big Beard's Adventure Tours",
    category: "snorkeling",
    kind: "tour",
    island: "stx",
    location: "Christiansted to Buck Island",
    duration: "Half or full day",
    summary: "An authorized Buck Island trip with guided reef snorkeling and beach time.",
    highlights: ["Buck Island", "Authorized operator", "Reef snorkel", "Catamaran"],
    sourceUrl: "https://www.bigbeards.com/",
    sourceLabel: "Operator website and National Park Service authorized-operator list",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-caribbean-sea-buck-island",
    name: "Buck Island Reef Snorkel",
    operator: "Caribbean Sea Adventures",
    category: "snorkeling",
    kind: "tour",
    island: "stx",
    location: "Christiansted to Buck Island",
    duration: "Half or full day",
    summary: "Authorized powerboat and sailing trips to Turtle Beach and Buck Island's underwater trail.",
    highlights: ["Buck Island", "Authorized operator", "Snorkel", "Boat tour"],
    sourceUrl: "https://caribbeanseaadventures.com/buck-island-tours/",
    sourceLabel: "Operator website and National Park Service authorized-operator list",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-caribbean-sea-parasail",
    name: "St. Croix Parasailing",
    operator: "Caribbean Sea Adventures",
    category: "parasailing",
    kind: "experience",
    island: "stx",
    location: "Christiansted, St. Croix",
    duration: "Varies",
    summary: "A parasailing experience over Christiansted's turquoise coastal water.",
    highlights: ["Parasailing", "Aerial views", "Waterfront", "Adventure"],
    sourceUrl: "https://caribbeanseaadventures.com/",
    sourceLabel: "Caribbean Sea Adventures official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-bushtribe-bio-bay",
    name: "Bioluminescent Bay Kayak",
    operator: "BushTribe Eco Adventures",
    category: "kayak",
    kind: "tour",
    island: "stx",
    location: "Salt River Bay, St. Croix",
    duration: "Evening tour",
    summary: "A small-group night paddle through St. Croix's bioluminescent bay, scheduled around viewing conditions.",
    highlights: ["Bioluminescence", "Night kayak", "Eco guide", "Seasonal conditions"],
    sourceUrl: "https://www.bushtribe.com/",
    sourceLabel: "BushTribe official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "seasonal",
  },
  {
    id: "stx-bushtribe-annaly",
    name: "Annaly Bay Tide Pools Hike",
    operator: "BushTribe Eco Adventures",
    category: "hiking",
    kind: "tour",
    island: "stx",
    location: "St. Croix North Shore",
    duration: "Half day",
    summary: "A guided rainforest and coastal hike to the Annaly Bay tide pools with terrain and condition guidance.",
    highlights: ["Hiking", "Tide pools", "Rainforest", "Guided"],
    sourceUrl: "https://www.bushtribe.com/",
    sourceLabel: "BushTribe official website",
    verifiedAt: "2026-08-09",
    availabilityStatus: "operator-listed",
  },
  {
    id: "stx-jolly-roger-buck-island",
    name: "Buck Island Charter",
    operator: "Jolly Roger Charters",
    category: "boat-charter",
    kind: "tour",
    island: "stx",
    location: "Christiansted Harbor",
    duration: "Varies",
    summary: "An authorized charter option serving Buck Island Reef National Monument.",
    highlights: ["Buck Island", "Authorized operator", "Charter", "Snorkeling"],
    sourceUrl: "http://www.jollyrogervi.com/",
    sourceLabel: "National Park Service authorized-operator list",
    verifiedAt: "2026-08-09",
    availabilityStatus: "request-only",
  },
  {
    id: "stx-llewellyn-buck-island",
    name: "Buck Island Sailing Charter",
    operator: "Llewellyn's Charters",
    category: "sailing",
    kind: "tour",
    island: "stx",
    location: "St. Croix Yacht Club",
    duration: "Varies",
    summary: "An authorized small-operator sailing option to Buck Island, reserved directly by phone.",
    highlights: ["Buck Island", "Authorized operator", "Sailing", "Small group"],
    sourceUrl: "https://www.nps.gov/buis/planyourvisit/directions.htm",
    sourceLabel: "National Park Service authorized-operator list",
    verifiedAt: "2026-08-09",
    availabilityStatus: "request-only",
  },
];

export const ACTIVITY_CATEGORY_LABELS: Record<ActivityCategory, string> = {
  "boat-charter": "Boat charters",
  snorkeling: "Snorkeling",
  scuba: "Scuba & SNUBA",
  kayak: "Kayaking",
  hiking: "Hiking",
  wildlife: "Wildlife encounters",
  zipline: "Zipline",
  parasailing: "Parasailing",
  sailing: "Sailing",
  cultural: "Culture",
};

export const ACTIVITY_COVERAGE_SOURCES = [
  {
    id: "visit-usvi-things-to-do",
    label: "Visit USVI Things to Do",
    url: "https://www.visitusvi.com/explore/things-to-do/",
    scope: "Territory-wide activities and tourism listings",
  },
  {
    id: "visit-usvi-water",
    label: "Visit USVI Water Activities",
    url: "https://www.visitusvi.com/explore/water-activities/",
    scope: "Water operators and activity categories",
  },
  {
    id: "nps-buck-island",
    label: "National Park Service Buck Island operators",
    url: "https://www.nps.gov/buis/planyourvisit/directions.htm",
    scope: "Authorized Buck Island operators",
  },
  {
    id: "operator-sites",
    label: "Operator official websites",
    url: "https://www.visitusvi.com/",
    scope: "Current offering, contact, and availability evidence",
  },
] as const;

export const ISLAND_NAMES: Record<IntelligenceIsland, string> = {
  stt: "St. Thomas",
  stj: "St. John",
  stx: "St. Croix",
};

export function getActivityCoverage() {
  return (["stt", "stj", "stx"] as const).map((island) => {
    const items = BOOKABLE_EXPERIENCES.filter((item) => item.island === island);
    return {
      island,
      count: items.length,
      operators: new Set(items.map((item) => item.operator)).size,
      categories: new Set(items.map((item) => item.category)).size,
    };
  });
}
