import fs from "node:fs";
import path from "node:path";
import { getAdminDb, hasFirebaseAdminConfiguration } from "../lib/firebase-admin";
import {
  auditTariffLocationCoverage,
  type TariffLocationMapping,
  type TariffResolvablePlace,
} from "../lib/tariff-location-resolver";
import type { OfficialTaxiTariff } from "../types/taxi-operations";

type UnknownRecord = Record<string, unknown>;
type Island = TariffResolvablePlace["island"];
type EndpointCatalog = { byName: Map<string,string>; byGeoid: Map<string,string>; ambiguousNames:Set<string>; endpointCount:number; ruleCount:number };
const ROOT=process.cwd();
const DEFAULT_INPUTS=["data/generated/geographic-dictionary-cleaned.json","data/generated/modern-estates.normalized.json","data/territory-coordinates.json"];
const MAPPINGS_PATH="data/tariff-location-mappings.reviewed.json";
const OUTPUT_PATH="data/generated/tariff-location-coverage-audit.json";
const REPORT_ONLY=process.env.TARIFF_COVERAGE_REPORT_ONLY==="1";
const ISLANDS:Island[]=["stt","stj","stx"];
const BLOCKED_ESTATE_NAME_INFERENCE=new Set(["stt:estate lindbergh bay","stt:estate dorothea","stt:dorothea estate"]);
function readJson(file:string):unknown{return JSON.parse(fs.readFileSync(path.join(ROOT,file),"utf8"));}
function records(value:unknown):UnknownRecord[]{if(Array.isArray(value))return value.filter((v):v is UnknownRecord=>!!v&&typeof v==="object");if(!value||typeof value!=="object")return[];const obj=value as UnknownRecord;for(const key of ["records","places","features","items","entries","data"])if(Array.isArray(obj[key]))return records(obj[key]);return[];}
function text(record:UnknownRecord,keys:string[]){for(const key of keys){const value=record[key];if(typeof value==="string"&&value.trim())return value.trim();}}
function normalize(value:string){return value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();}
function islandCode(record:UnknownRecord):Island|undefined{const raw=text(record,["islandCode","island","island_id","islandId"])?.toLowerCase().replace(/[^a-z0-9]/g,"");if(!raw)return;if(["stt","stthomas","saintthomas"].includes(raw))return"stt";if(["stj","stjohn","saintjohn"].includes(raw))return"stj";if(["stx","stcroix","saintcroix"].includes(raw))return"stx";}
function toPlace(record:UnknownRecord,source:string,index:number):TariffResolvablePlace|undefined{const island=islandCode(record);const name=text(record,["name","displayName","title","label","fullName","estate"]);if(!island||!name)return;const id=text(record,["id","placeId","slug","geoid","key"])??`${source}:${index}:${name}`;return{id,island,name,tariffEndpointName:text(record,["tariffEndpointName","tariff_endpoint","tariffEndpoint"]),parentPlaceId:text(record,["parentPlaceId","parent_id","parentId"])};}
function addCatalogName(c:EndpointCatalog,name:string){const key=normalize(name);if(!key)return;const existing=c.byName.get(key);if(existing&&normalize(existing)!==key){c.ambiguousNames.add(key);c.byName.delete(key);return;}if(!c.ambiguousNames.has(key))c.byName.set(key,name);}
function addRuleSide(c:EndpointCatalog,names:string[]|undefined,geoids:string[]|undefined){const ns=(names??[]).filter(n=>typeof n==="string"&&n.trim());for(const n of ns)addCatalogName(c,n);const primary=ns[0];if(primary)for(const g of geoids??[])if(typeof g==="string"&&g.trim())c.byGeoid.set(g.trim(),primary);}
function buildCatalog(tariffs:OfficialTaxiTariff[]){const catalogs=Object.fromEntries(ISLANDS.map(i=>[i,{byName:new Map(),byGeoid:new Map(),ambiguousNames:new Set(),endpointCount:0,ruleCount:0}])) as Record<Island,EndpointCatalog>;for(const tariff of tariffs){if(!ISLANDS.includes(tariff.island))continue;const c=catalogs[tariff.island];for(const rule of tariff.rules??[]){c.ruleCount++;addRuleSide(c,rule.originNames,rule.originEstateGeoids);addRuleSide(c,rule.destinationNames,rule.destinationEstateGeoids);}}for(const i of ISLANDS)catalogs[i].endpointCount=catalogs[i].byName.size;return catalogs;}
async function loadActiveTariffs(){if(!hasFirebaseAdminConfiguration())return{tariffs:[] as OfficialTaxiTariff[],status:"unavailable" as const,reason:"Firebase Admin configuration is not available."};try{const snapshot=await getAdminDb().collection("taxiTariffs").where("status","==","active").get();return{tariffs:snapshot.docs.map(d=>({id:d.id,...d.data()}) as OfficialTaxiTariff),status:"loaded" as const};}catch(error){return{tariffs:[] as OfficialTaxiTariff[],status:"error" as const,reason:error instanceof Error?error.message:"Unknown Firestore tariff catalog error."};}}
function safePlaceCandidates(place:TariffResolvablePlace){const raw=normalize(place.name);const candidates=[raw];if(!BLOCKED_ESTATE_NAME_INFERENCE.has(`${place.island}:${raw}`)&&raw.startsWith("estate ")&&raw.length>7)candidates.push(raw.slice(7));return[...new Set(candidates)];}
function attachGovernedEndpointIdentity(place:TariffResolvablePlace,catalogs:Record<Island,EndpointCatalog>){if(place.tariffEndpointName)return place;const c=catalogs[place.island];const geoid=c.byGeoid.get(place.id);if(geoid)return{...place,tariffEndpointName:geoid};const matches=safePlaceCandidates(place).map(x=>c.byName.get(x)).filter((x):x is string=>!!x);const unique=[...new Map(matches.map(x=>[normalize(x),x])).values()];return unique.length===1?{...place,tariffEndpointName:unique[0]}:place;}
async function main(){const places=new Map<string,TariffResolvablePlace>();for(const input of DEFAULT_INPUTS){const full=path.join(ROOT,input);if(!fs.existsSync(full))continue;records(readJson(input)).forEach((r,index)=>{const p=toPlace(r,input,index);if(p)places.set(`${p.island}:${p.id}`,p);});}const mappings:TariffLocationMapping[]=fs.existsSync(path.join(ROOT,MAPPINGS_PATH))?(readJson(MAPPINGS_PATH) as TariffLocationMapping[]):[];const active=await loadActiveTariffs();const catalogs=buildCatalog(active.tariffs);const governed=[...places.values()].map(p=>attachGovernedEndpointIdentity(p,catalogs));const audit=auditTariffLocationCoverage(governed,mappings);
const byIsland=Object.fromEntries(ISLANDS.map(island=>{const subset=audit.resolutions.filter(r=>r.island===island);const unresolved=subset.filter(r=>r.method==="unresolved").length;const publishedFareAvailable=catalogs[island].ruleCount>0;return[island,{total:subset.length,resolved:subset.length-unresolved,unresolved,publishedFareAvailable,verificationRequired:publishedFareAvailable?unresolved:subset.length,safeDisposition:subset.length}];}));
const publishedFareIslands=ISLANDS.filter(i=>catalogs[i].ruleCount>0);const publishedFarePopulation=audit.resolutions.filter(r=>publishedFareIslands.includes(r.island));const publishedFareResolved=publishedFarePopulation.filter(r=>r.method!=="unresolved").length;const verificationRequired=audit.resolutions.filter(r=>catalogs[r.island].ruleCount===0||r.method==="unresolved").length;const unsafeUnknown=audit.resolutions.filter(r=>r.method==="unresolved"&&catalogs[r.island].ruleCount>0).length;
const report={generatedAt:new Date().toISOString(),policy:"Every selectable taxi destination must end in one of two safe states: a traceable governed tariff endpoint, or verification_required / official_tariff_unavailable. Never infer a fare from proximity, fuzzy matching, or an unpublished tariff. Water Island remains in its dedicated ferry/mobility flow.",inputs:DEFAULT_INPUTS,mappings:MAPPINGS_PATH,tariffCatalogStatus:active.status,tariffCatalogReason:active.reason,activeTariffCount:active.tariffs.length,catalogSummary:Object.fromEntries(ISLANDS.map(i=>[i,{endpointCount:catalogs[i].endpointCount,ruleCount:catalogs[i].ruleCount,geoidBindings:catalogs[i].byGeoid.size,ambiguousCanonicalNames:catalogs[i].ambiguousNames.size}])),total:audit.total,governedFareResolved:audit.resolved,verificationRequired,unsafeUnknown,publishedFareCoverage:{population:publishedFarePopulation.length,resolved:publishedFareResolved,coverage:publishedFarePopulation.length?publishedFareResolved/publishedFarePopulation.length:1},safeDispositionCoverage:1,byIsland,unresolvedPlaces:audit.unresolvedPlaces};fs.mkdirSync(path.dirname(path.join(ROOT,OUTPUT_PATH)),{recursive:true});fs.writeFileSync(path.join(ROOT,OUTPUT_PATH),`${JSON.stringify(report,null,2)}\n`);console.log(JSON.stringify({...report,unresolvedPlaces:undefined},null,2));if(!REPORT_ONLY&&(active.status!=="loaded"||unsafeUnknown>0))process.exitCode=2;}
main().catch(error=>{console.error(error);process.exitCode=REPORT_ONLY?0:2;});
