import fs from "node:fs";
import path from "node:path";
import { geographicIndex } from "../src/data/core/geographicIndex";

type IslandCode = "st_thomas" | "st_john" | "st_croix" | "water_island";

type AnyRecord = Record<string, any>;

const OUTPUT_DIR = "src/data/historyGraph";
const OUTPUT_FILE = path.join(OUTPUT_DIR, "colonialEstates.ts");

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, "and")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function normalizeIsland(value: unknown): IslandCode | null {
  const raw = String(value ?? "").toLowerCase().trim();

  if (["st_thomas", "stt", "st. thomas", "st thomas", "saint thomas"].includes(raw)) return "st_thomas";
  if (["st_john", "stj", "st. john", "st john", "saint john", "st jan"].includes(raw)) return "st_john";
  if (["st_croix", "stx", "st. croix", "st croix", "saint croix"].includes(raw)) return "st_croix";
  if (["water_island", "wat", "water island"].includes(raw)) return "water_island";

  return null;
}

function getItems(): AnyRecord[] {
  const input: any = geographicIndex;
  if (Array.isArray(input)) return input;
  if (Array.isArray(input.items)) return input.items;
  throw new Error("geographicIndex.items was not found.");
}

function getCoordinates(record: AnyRecord) {
  const c = record.coordinates ?? record.centroid;

  if (Array.isArray(c) && typeof c[0] === "number" && typeof c[1] === "number") {
    return { lng: c[0], lat: c[1] };
  }

  if (c && typeof c.lat === "number" && typeof c.lng === "number") {
    return { lat: c.lat, lng: c.lng };
  }

  return null;
}

function isOfficialEstate(record: AnyRecord): boolean {
  // Official canonical estate records from geographicIndex.
  // Source counts confirm: source === "estate" gives 415.
  return record.source === "estate";
}

const estateRecords = getItems().filter(isOfficialEstate);

const records = estateRecords
  .map((record) => {
    const name =
      record.canonicalName ??
      record.displayName ??
      record.baseName ??
      record.name ??
      record.estateName;

    const island = normalizeIsland(record.island);

    if (!name || !island) return null;

    return {
      id: slugify(String(record.id ?? record.geoid ?? `${island}_${name}`)),
      name: String(name),
      aliases: Array.isArray(record.aliases) ? record.aliases : [],
      island,
      quarter: record.quarter ?? record.quarterName ?? record.quarterGroup ?? null,
      modernEstate: String(name),
      geoid: record.geoid ?? record.GEOID ?? null,
      coordinates: getCoordinates(record),
      confidence: "confirmed",
      needs_owner_chain: true,
    };
  })
  .filter(Boolean)
  .sort((a: any, b: any) => {
    if (a.island !== b.island) return a.island.localeCompare(b.island);
    return a.name.localeCompare(b.name);
  });

const byIsland = records.reduce(
  (acc: Record<IslandCode, number>, record: any) => {
    acc[record.island] += 1;
    return acc;
  },
  { st_thomas: 0, st_john: 0, st_croix: 0, water_island: 0 }
);

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

fs.writeFileSync(
  OUTPUT_FILE,
  `// Auto-generated by scripts/build-colonial-estates.ts
// Rebuild with: npm run history:colonial-estates:build

export type IslandCode = "st_thomas" | "st_john" | "st_croix" | "water_island";
export type ColonialEstateConfidence = "confirmed" | "probable" | "possible";

export interface ColonialEstateRecord {
  id: string;
  name: string;
  aliases: string[];
  island: IslandCode;
  quarter: string | null;
  modernEstate: string;
  geoid: string | null;
  coordinates: { lat: number; lng: number } | null;
  confidence: ColonialEstateConfidence;
  needs_owner_chain: true;
}

export const colonialEstateSummary = ${JSON.stringify(
    {
      total: records.length,
      byIsland,
      sourceTotalEstates: (geographicIndex as any).counts?.estates ?? null,
      generatedAt: new Date().toISOString(),
    },
    null,
    2
  )} as const;

export const colonialEstates: ColonialEstateRecord[] = ${JSON.stringify(records, null, 2)};
`
);

console.log("Colonial estates built.");
console.log({
  output: OUTPUT_FILE,
  total: records.length,
  byIsland,
  sourceTotalEstates: (geographicIndex as any).counts?.estates,
});
