import fs from "node:fs/promises";
import path from "node:path";

type GeographicDictionaryEntry = {
  id: string; slug: string; canonicalName: string; normalizedName?: string; featureType: string; island: string;
  quarter?: string | null; description?: string; shortDescription?: string; rawText?: string; aliases?: string[];
  obsoleteNames?: string[]; variantSpellings?: string[]; linguisticEquivalents?: string[]; relatedEntryIds?: string[];
  relatedHistoricSiteIds?: string[]; relatedEstateGeoids?: string[]; relatedPlaceIds?: string[]; searchTokens?: string[];
  parseWarnings?: string[]; parseConfidence?: number; needsReview?: boolean; createdAt?: string; updatedAt?: string;
  verification?: DictionaryVerification; [key: string]: unknown;
};
type DictionaryVerification = { normalizedName: string; canonicalName?: string; island?: string; relationship?: string; relatedName?: string; confidence: "high"|"medium"|"low"; evidence: string; source: string };
const INPUT_PATH=path.join(process.cwd(),"data","generated","geographic-dictionary-normalized.json");
const OUTPUT_PATH=path.join(process.cwd(),"data","generated","geographic-dictionary-cleaned.json");
const REVIEW_PATH=path.join(process.cwd(),"data","generated","geographic-dictionary-review.json");
const SUMMARY_PATH=path.join(process.cwd(),"data-products","usvi-geographic-intelligence","reports","dictionary-integrity-summary.json");
const OVERRIDE_PATH=path.join(process.cwd(),"data","derived","geographic-dictionary-verification-overrides.json");
const BLOCKED_NAME_FRAGMENTS=["GEOGRAPHICDICTIONARY","GEOGRAPHIC DICTIONARY","VIRGIN ISLANDS","U.S.COAST","U.S. COAST","COASTANDGEODETIC","COAST AND GEODETIC","DEPARTMENT OF COMMERCE","COAST PILOT","GOVERNMENT PRINTING OFFICE","WASHINGTON","ERRATA NOTICE","PREFACE","CONTENTS"];
const NARRATIVE_NAME_FRAGMENTS=["thevegetationof","theclimate","thegroupwas","theviewof","theislandsare","publicschools","grammar school","junior high","populationabout","totalpopulation"];
const BAD_PREFIXES=["U.S.","U S ","GEOGRAPHIC","DEPARTMENT","CONTENTS","PREFACE"];
const ALLOWED_ISLANDS=new Set(["STT","STJ","STX","UNKNOWN"]);
const FEATURE_TYPE_KEYWORDS:Record<string,string[]>={bay:[" bay"," cove"," harbor"," harbour"," bight"," sound"],harbor:[" harbor"," harbour"," basin"," roadstead"],point:[" point"," pointe"," bluff"," cape"," head"],estate:[" estate"," plantation"," plantage"," quarter"],hill:[" hill"," mountain"," peak"," ridge"," knoll"," berg"],road:[" road"," lane"," path"," way"," trail"],gut:[" gut"," ghaut"],cay:[" cay"," key"," island"," islet"," rock"],quarter:[" quarter"," district"],harbor_feature:[" wharf"," dock"," landing"]};
function normalizeWhitespace(v:string){return v.replace(/\s+/g," ").trim()}
function normalizeGeoText(v:string){return normalizeWhitespace(v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[‘’'\"]/g,"").replace(/&/g," and ").replace(/[^a-zA-Z0-9.\- ]+/g," ").toLowerCase())}
function titleCaseLoose(v:string){return normalizeWhitespace(v.toLowerCase().split(" ").map(p=>!p?p:p==="st."||p==="st"?"St.":p==="u.s."||p==="us"?"U.S.":p[0].toUpperCase()+p.slice(1)).join(" "))}
function stripLeadingNoise(v:string){return normalizeWhitespace(v.replace(/^[0-9&.,;:()\- ]+/,"").replace(/^(and|the)\s+/i,""))}
function cleanCanonicalName(v:string){v=normalizeWhitespace(v).replace(/\s*;\s*$/,"").replace(/\s*\.\s*$/,"").replace(/^[^A-Za-z0-9(]+/,"").replace(/[^A-Za-z0-9.)]+$/,"");v=stripLeadingNoise(v);if(/^[A-Z0-9.\-()]+$/.test(v)&&!/^St\./.test(v))v=titleCaseLoose(v);return normalizeWhitespace(v)}
function looksLikeNarrativeArtifact(v:string){const n=normalizeGeoText(v).replace(/\s+/g,"");if(NARRATIVE_NAME_FRAGMENTS.some(f=>n.includes(f.replace(/\s+/g,""))))return true;if(v.length>=45&&!/\s/.test(v))return true;return (v.match(/[A-Za-z]{10,}/g)||[]).length>=3&&v.length>=55}
function looksLikeHeaderOrJunkName(v:string){const u=v.toUpperCase();if(!v||v.length<3||v.length>90||(v.match(/[^A-Za-z0-9 .,'()\-]/g)||[]).length>=4)return true;if((v.match(/[.;:()]/g)||[]).length>=4||/[0-9]{3,}/.test(v)||/^[^A-Za-z]+$/.test(v))return true;if(BLOCKED_NAME_FRAGMENTS.some(x=>u.includes(x))||BAD_PREFIXES.some(x=>u.startsWith(x)))return true;return looksLikeNarrativeArtifact(v)}
function looksLikeMergedParagraph(v:string){const c=v.replace(/\s/g,"");return c.length>45&&(!v.includes(" ")||/[a-z]{8,}[A-Z][a-z]{5,}/.test(v))}
function inferIsland(e:GeographicDictionaryEntry){const t=`${e.canonicalName} ${e.shortDescription||""} ${e.description||""} ${e.rawText||""}`.toUpperCase();const a=/\bST\.\s*THOMAS\b|\bST THOMAS\b/.test(t),b=/\bST\.\s*JOHN\b|\bST JOHN\b/.test(t),c=/\bST\.\s*CROIX\b|\bST CROIX\b/.test(t);if(a&&!b&&!c)return"STT";if(b&&!a&&!c)return"STJ";if(c&&!a&&!b)return"STX";return e.island&&ALLOWED_ISLANDS.has(e.island)?e.island:"UNKNOWN"}
function inferFeatureType(e:GeographicDictionaryEntry){const h=normalizeGeoText(`${e.canonicalName} ${e.shortDescription||""} ${e.description||""}`);for(const [t,ks] of Object.entries(FEATURE_TYPE_KEYWORDS))if(ks.some(k=>h.includes(k.trim())))return t==="harbor_feature"?"harbor":t;return e.featureType||"place"}
function dedupeStrings(v:string[]|undefined){const s=new Set<string>(),o:string[]=[];for(const x of v||[]){const c=normalizeWhitespace(x||""),k=normalizeGeoText(c);if(c&&k&&!s.has(k)){s.add(k);o.push(c)}}return o}
function buildSearchTokens(e:GeographicDictionaryEntry){const s=new Set<string>();const add=(v?:string)=>{const c=normalizeGeoText(v||"");if(!c)return;s.add(c);for(const p of c.split(" "))if(p.length>=3)s.add(p)};add(e.canonicalName);add(e.normalizedName);add(e.shortDescription);add(e.description);for(const v of [...(e.aliases||[]),...(e.variantSpellings||[]),...(e.obsoleteNames||[]),...(e.linguisticEquivalents||[])])add(v);return Array.from(s).slice(0,80)}
function scoreEntry(e:GeographicDictionaryEntry){let s=100;if(e.parseConfidence!=null)s+=Math.round((e.parseConfidence-1)*20);if(e.island==="UNKNOWN")s-=15;if(e.needsReview)s-=10;if(looksLikeMergedParagraph(e.canonicalName))s-=50;if((e.canonicalName.match(/[.()]/g)||[]).length>=3)s-=20;if((e.shortDescription||"").length<12)s-=5;if((e.description||"").length<20)s-=5;return s}
function applyVerification(e:GeographicDictionaryEntry,o?:DictionaryVerification){if(!o)return e;const aliases=dedupeStrings([...(e.aliases||[]),...(o.canonicalName&&normalizeGeoText(o.canonicalName)!==normalizeGeoText(e.canonicalName)?[e.canonicalName]:[])]);return {...e,canonicalName:o.canonicalName||e.canonicalName,normalizedName:normalizeGeoText(o.canonicalName||e.canonicalName),island:o.island&&ALLOWED_ISLANDS.has(o.island)?o.island:e.island,aliases,verification:o}}
function cleanEntry(entry:GeographicDictionaryEntry,override?:DictionaryVerification){const canonicalName=cleanCanonicalName(entry.canonicalName||"");if(looksLikeHeaderOrJunkName(canonicalName))return null;let cleaned:GeographicDictionaryEntry={...entry,canonicalName,slug:normalizeGeoText(canonicalName).replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||entry.id,normalizedName:normalizeGeoText(canonicalName),shortDescription:normalizeWhitespace(entry.shortDescription||entry.description||""),description:normalizeWhitespace(entry.description||entry.shortDescription||""),island:inferIsland({...entry,canonicalName}),featureType:inferFeatureType({...entry,canonicalName}),aliases:dedupeStrings(entry.aliases),obsoleteNames:dedupeStrings(entry.obsoleteNames),variantSpellings:dedupeStrings(entry.variantSpellings),linguisticEquivalents:dedupeStrings(entry.linguisticEquivalents),relatedEntryIds:Array.isArray(entry.relatedEntryIds)?entry.relatedEntryIds:[],relatedHistoricSiteIds:Array.isArray(entry.relatedHistoricSiteIds)?entry.relatedHistoricSiteIds:[],relatedEstateGeoids:Array.isArray(entry.relatedEstateGeoids)?entry.relatedEstateGeoids:[],relatedPlaceIds:Array.isArray(entry.relatedPlaceIds)?entry.relatedPlaceIds:[],quarter:typeof entry.quarter==="string"?normalizeWhitespace(entry.quarter):null};cleaned=applyVerification(cleaned,override);cleaned.searchTokens=buildSearchTokens(cleaned);cleaned.parseConfidence=typeof cleaned.parseConfidence==="number"?cleaned.parseConfidence:1;const w=new Set(cleaned.parseWarnings||[]);if(cleaned.island==="UNKNOWN")w.add("Island not inferred");else w.delete("Island not inferred");if(looksLikeMergedParagraph(cleaned.canonicalName))w.add("Possible merged OCR text");if(override)w.add(`Verified ${override.confidence}: ${override.source}`);cleaned.parseWarnings=Array.from(w);const q=scoreEntry(cleaned);cleaned.needsReview=q<65||cleaned.parseWarnings.filter(x=>!x.startsWith("Verified ")).length>1||override?.confidence==="low";return{cleaned,qualityScore:q}}
function buildIntegritySummary(entries:GeographicDictionaryEntry[],review:GeographicDictionaryEntry[],dropped:Array<{id:string;canonicalName:string}>,overrides:DictionaryVerification[]){
  const unknownIsland=entries.filter(e=>e.island==="UNKNOWN");
  const lowConfidence=entries.filter(e=>(e.parseConfidence??1)<0.75);
  const unresolvedEstateLike=review.filter(e=>e.featureType==="estate"||/\bestate\b|\bplantation\b|\bplantage\b/i.test(`${e.description||""} ${e.rawText||""}`));
  return {
    generatedAt:new Date().toISOString(),
    inputPolicy:"1925 dictionary OCR is cleaned fail-closed; verified corrections are applied from the override ledger; unresolved records remain review-only.",
    totals:{cleaned:entries.length,dropped:dropped.length,verifiedOverrides:overrides.length,needsReview:review.length,unknownIsland:unknownIsland.length,lowConfidence:lowConfidence.length,unresolvedEstateLike:unresolvedEstateLike.length},
    releaseGate:{passes:review.length===0&&unknownIsland.length===0,rule:"Commercial dictionary export must contain zero needsReview records and zero UNKNOWN island assignments."},
    unresolved:{unknownIsland:unknownIsland.map(e=>({id:e.id,name:e.canonicalName,featureType:e.featureType,warnings:e.parseWarnings||[]})),estateLike:unresolvedEstateLike.map(e=>({id:e.id,name:e.canonicalName,island:e.island,warnings:e.parseWarnings||[]}))},
  };
}
export const dictionaryCleanerInternals={cleanCanonicalName,looksLikeHeaderOrJunkName,looksLikeNarrativeArtifact,inferIsland,applyVerification,buildIntegritySummary};
async function main(){const [raw,overrideRaw]=await Promise.all([fs.readFile(INPUT_PATH,"utf8"),fs.readFile(OVERRIDE_PATH,"utf8").catch(()=>"[]")]);const entries=JSON.parse(raw) as GeographicDictionaryEntry[],overrides=JSON.parse(overrideRaw) as DictionaryVerification[];const byName=new Map(overrides.map(o=>[normalizeGeoText(o.normalizedName),o]));const cleaned:GeographicDictionaryEntry[]=[],review:Array<GeographicDictionaryEntry&{qualityScore:number}>=[],dropped:Array<{id:string;canonicalName:string}>=[];for(const entry of entries){const result=cleanEntry(entry,byName.get(normalizeGeoText(entry.normalizedName||entry.canonicalName)));if(!result){dropped.push({id:entry.id,canonicalName:entry.canonicalName});continue}cleaned.push(result.cleaned);if(result.cleaned.needsReview)review.push({...result.cleaned,qualityScore:result.qualityScore})}cleaned.sort((a,b)=>a.canonicalName.localeCompare(b.canonicalName));review.sort((a,b)=>a.qualityScore-b.qualityScore);const summary=buildIntegritySummary(cleaned,review,dropped,overrides);await fs.mkdir(path.dirname(SUMMARY_PATH),{recursive:true});await Promise.all([fs.writeFile(OUTPUT_PATH,JSON.stringify(cleaned,null,2),"utf8"),fs.writeFile(REVIEW_PATH,JSON.stringify(review,null,2),"utf8"),fs.writeFile(SUMMARY_PATH,JSON.stringify(summary,null,2),"utf8")]);console.log(`Input entries: ${entries.length}`);console.log(`Cleaned entries: ${cleaned.length}`);console.log(`Dropped entries: ${dropped.length}`);console.log(`Verified overrides applied: ${overrides.length}`);console.log(`Needs review: ${review.length}`);console.log(`Unknown island: ${summary.totals.unknownIsland}`);console.log(`Unresolved estate-like: ${summary.totals.unresolvedEstateLike}`);console.log(`Commercial release gate: ${summary.releaseGate.passes?"PASS":"BLOCKED"}`)}
if(process.argv[1]?.endsWith("clean-geographic-dictionary.ts"))main().catch(e=>{console.error("Geographic dictionary cleanup failed:",e);process.exit(1)});
