import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

type AnyRecord = Record<string, any>;

const ROOT = process.cwd();
const SOURCE_FILE = path.join(ROOT, "src/data/core/geographicIndex.ts");
const BACKUP_DIR = path.join(ROOT, "reports/backups");
const REMOVED_REPORT = path.join(ROOT, "reports/removed-geographic-index-records.json");

const ARRAY_EXPORT_CANDIDATES = [
  "geographicIndex",
  "GEOGRAPHIC_INDEX",
  "items",
  "records",
];

const NAME_FIELDS = [
  "name",
  "title",
  "label",
  "term",
  "entry",
  "estate",
  "estateName",
  "fullName",
  "baseName",
  "displayName",
  "siteName",
  "placeName",
];

function getFirstString(record: AnyRecord, fields: string[]) {
  for (const field of fields) {
    const value = record[field];

    if (typeof value === "string" && value.trim()) {
      return value.trim();
    }

    if (typeof value === "number" && Number.isFinite(value)) {
      return String(value);
    }
  }

  return undefined;
}

function normalizeName(value: string) {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function isClearlyBadGeneratedRecord(record: AnyRecord) {
  const name = getFirstString(record, NAME_FIELDS);

  if (!name) return false;

  const normalized = normalizeName(name);

  if (normalized.length <= 1) return true;

  const badExactNames = new Set([
    "undefined",
    "null",
    "unknown",
    "n a",
    "todo",
    "tbd",
  ]);

  if (badExactNames.has(normalized)) return true;

  return false;
}

async function loadGeographicIndex() {
  if (!existsSync(SOURCE_FILE)) {
    throw new Error(`Missing file: ${path.relative(ROOT, SOURCE_FILE)}`);
  }

  const mod = await import(`${pathToFileURL(SOURCE_FILE).href}?cacheBust=${Date.now()}`);

  for (const exportName of ARRAY_EXPORT_CANDIDATES) {
    if (Array.isArray(mod[exportName])) {
      return {
        exportName,
        records: mod[exportName] as AnyRecord[],
      };
    }
  }

  for (const [exportName, value] of Object.entries(mod)) {
    if (Array.isArray(value)) {
      return {
        exportName,
        records: value as AnyRecord[],
      };
    }
  }

  throw new Error(
    `Could not find an array export in ${path.relative(ROOT, SOURCE_FILE)}.`,
  );
}

function stableStringify(value: unknown) {
  return JSON.stringify(value, null, 2);
}

function makeOutput(records: AnyRecord[]) {
  const generatedAt = new Date().toISOString();

  return `// Auto-sanitized geographic index.
// Generated by scripts/sanitize-geographic-index.ts.
// If this file is regenerated by another build script, run this sanitizer again
// or move the same junk-record filter into the upstream builder.

export type GeographicIndexItem = {
  id?: string;
  geoid?: string;
  slug?: string;
  estateId?: string;
  displayName?: string;
  aliases?: string[];
  name?: string;
  title?: string;
  label?: string;
  island?: string;
  islandCode?: string;
  type?: string;
  kind?: string;
  category?: string;
  description?: string;
  history?: string;
  significance?: string;
  estate?: string;
  estateName?: string;
  quarter?: string;
  quarterGroup?: string;
  lat?: number;
  lng?: number;
  latitude?: number;
  longitude?: number;
  coords?: any;
  coordinates?: any;
  center?: any;
  centroid?: any;
  image?: string;
  imageUrl?: string;
  thumbnail?: string;
  thumbnailUrl?: string;
  source?: string;
  tags?: string[];
  [key: string]: unknown;
};

export type GeographicIndexRecord = GeographicIndexItem;
export type GeographicRecord = GeographicIndexItem;
export type AtlasRecord = GeographicIndexItem;
export type AtlasItem = GeographicIndexItem;

export const geographicIndexGeneratedAt = ${JSON.stringify(generatedAt)};

export const geographicIndex: GeographicIndexItem[] = ${stableStringify(records)};

export const geographicIndexItems = geographicIndex;
export const GEOGRAPHIC_INDEX_ITEMS = geographicIndex;
export const GEOGRAPHIC_INDEX = geographicIndex;
export const items = geographicIndex;
export const records = geographicIndex;

export const geographicIndexMeta = {
  generatedAt: geographicIndexGeneratedAt,
  totalRecords: geographicIndex.length,
  sanitized: true,
};

export const GEOGRAPHIC_INDEX_META = geographicIndexMeta;

export default geographicIndex;
`;
}

async function main() {
  mkdirSync(BACKUP_DIR, { recursive: true });
  mkdirSync(path.join(ROOT, "reports"), { recursive: true });

  const backupFile = path.join(
    BACKUP_DIR,
    `geographicIndex.${new Date().toISOString().replace(/[:.]/g, "-")}.ts`,
  );

  copyFileSync(SOURCE_FILE, backupFile);

  const { exportName, records } = await loadGeographicIndex();

  const removed: Array<{
    originalIndex: number;
    name?: string;
    id?: string;
    type?: string;
    island?: string;
    record: AnyRecord;
  }> = [];

  const cleaned = records.filter((record, originalIndex) => {
    if (!isClearlyBadGeneratedRecord(record)) return true;

    removed.push({
      originalIndex,
      name: getFirstString(record, NAME_FIELDS),
      id: record.id ?? record.geoid ?? record.slug,
      type: record.type ?? record.kind ?? record.category,
      island: record.island ?? record.islandCode,
      record,
    });

    return false;
  });

  writeFileSync(REMOVED_REPORT, stableStringify(removed));
  writeFileSync(SOURCE_FILE, makeOutput(cleaned));

  console.log("Geographic index sanitized.");
  console.log(`Array export used: ${exportName}`);
  console.log(`Before: ${records.length}`);
  console.log(`After: ${cleaned.length}`);
  console.log(`Removed: ${removed.length}`);
  console.log(`Backup: ${path.relative(ROOT, backupFile)}`);
  console.log(`Removed report: ${path.relative(ROOT, REMOVED_REPORT)}`);

  if (removed.length > 0) {
    console.table(
      removed.map((item) => ({
        originalIndex: item.originalIndex,
        name: item.name,
        id: item.id,
        type: item.type,
        island: item.island,
      })),
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
