"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Briefcase, CalendarDays, CarFront, Check, ExternalLink, MapPin, Plane, Sailboat, Sparkles, Star, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { rankCarRentalOperators, type CarRentalArrival, type CarRentalIsland, type CarRentalVehicleNeed } from "@/lib/car-rentals";

type VehicleNeed = "auto" | CarRentalVehicleNeed;
type RentalPlan = { island: CarRentalIsland | ""; arrival: CarRentalArrival | ""; pickupDate: string; dropoffDate: string; travelers: number; luggage: number; vehicleNeed: VehicleNeed };
const INITIAL_PLAN: RentalPlan = { island: "", arrival: "", pickupDate: "", dropoffDate: "", travelers: 2, luggage: 2, vehicleNeed: "auto" };
const STEPS = ["Island", "Arrival", "Dates", "Travelers", "Vehicle", "Match"] as const;
const ISLANDS = [{ value: "stt" as const, label: "St. Thomas", detail: "Airport, Charlotte Amalie, Red Hook" }, { value: "stj" as const, label: "St. John", detail: "Cruz Bay ferry arrival and 4x4-heavy driving" }, { value: "stx" as const, label: "St. Croix", detail: "Airport, Christiansted, Frederiksted" }];
const ARRIVALS = [{ value: "airport" as const, label: "Airport", detail: "Match pickup to your flight", icon: Plane }, { value: "ferry" as const, label: "Ferry", detail: "Match pickup to the correct terminal", icon: Sailboat }, { value: "local" as const, label: "Already on island", detail: "Hotel, villa, town, or local pickup", icon: MapPin }];
const VEHICLES: Array<{ value: VehicleNeed; label: string; detail: string }> = [{ value: "auto", label: "Recommend for me", detail: "Use my group, bags, island, and arrival" }, { value: "car", label: "Car", detail: "Efficient for lighter luggage and paved routes" }, { value: "suv", label: "SUV", detail: "More room for luggage, hills, and comfort" }, { value: "jeep", label: "Jeep / 4x4", detail: "Strong fit for St. John and rougher access" }, { value: "van", label: "Passenger van", detail: "Best for larger groups and lots of luggage" }];

export function RentalDecisionLauncher() {
  const [step, setStep] = useState(0);
  const [plan, setPlan] = useState<RentalPlan>(INITIAL_PLAN);
  const recommendation = useMemo(() => getRecommendation(plan), [plan]);
  const matchedVehicle = (plan.vehicleNeed === "auto" ? recommendation.vehicle : plan.vehicleNeed) as CarRentalVehicleNeed;
  const matches = useMemo(() => plan.island ? rankCarRentalOperators({ island: plan.island, arrival: plan.arrival || undefined, vehicle: matchedVehicle, travelers: plan.travelers, luggage: plan.luggage }) : [], [plan, matchedVehicle]);
  const canContinue = getStepReady(step, plan);
  const conciergePrompt = useMemo(() => buildConciergePrompt(plan, recommendation.label, matches.slice(0, 3).map((match) => match.operator.name)), [plan, recommendation.label, matches]);

  return <section className="mx-auto max-w-7xl px-4 pt-10 sm:px-7 lg:px-10 lg:pt-14" aria-labelledby="rental-start-title">
    <div className="overflow-hidden rounded-[34px] border border-[#cfe0dc] bg-[#fffdf8] shadow-[0_20px_60px_rgba(3,47,45,.09)]">
      <div className="grid lg:grid-cols-[1fr_340px]">
        <div className="p-5 sm:p-8 lg:p-10">
          <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="vi-eyebrow text-[#0f766e]">Guided rental match</p><h2 id="rental-start-title" className="vi-display mt-2 text-3xl font-bold sm:text-5xl">Build the right rental around your trip.</h2><p className="mt-3 max-w-2xl text-sm font-semibold leading-6 text-slate-600">We use your island, arrival, dates, party, luggage, and vehicle needs to rank the verified operators that fit best.</p></div><span className="rounded-full bg-[#e8f5f2] px-4 py-2 text-[9px] font-black uppercase tracking-[.14em] text-[#0f766e]">Step {step + 1} of {STEPS.length}</span></div>
          <div className="mt-7 grid grid-cols-6 gap-1.5">{STEPS.map((label, index) => <button key={label} type="button" onClick={() => index <= step && setStep(index)} className="text-left"><span className={`block h-1.5 rounded-full ${index <= step ? "bg-[#0f766e]" : "bg-[#dce7e4]"}`} /><span className={`mt-2 hidden text-[8px] font-black uppercase tracking-[.1em] sm:block ${index === step ? "text-[#032f2d]" : "text-slate-400"}`}>{label}</span></button>)}</div>
          <div className="mt-8 min-h-[315px]">
            {step === 0 && <ChoiceStep title="Which island will you drive?" subtitle="Choose the island where the rental will be picked up." options={ISLANDS.map((item) => ({ ...item, selected: plan.island === item.value, onClick: () => setPlan((p) => ({ ...p, island: item.value, arrival: item.value === "stj" && p.arrival === "airport" ? "ferry" : p.arrival })) }))} />}
            {step === 1 && <div><StepTitle title="How are you arriving?" subtitle="Pickup fit is one of the strongest signals in the operator ranking." /><div className="mt-6 grid gap-3 sm:grid-cols-3">{ARRIVALS.filter((item) => !(plan.island === "stj" && item.value === "airport")).map(({ value, label, detail, icon: Icon }) => <button key={value} type="button" onClick={() => setPlan((p) => ({ ...p, arrival: value }))} className={`rounded-[24px] border p-5 text-left ${plan.arrival === value ? "border-[#0f766e] bg-[#eaf8f5]" : "border-[#dce7e4] bg-white"}`}><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#032f2d] text-[#73e3d9]"><Icon size={20} /></span><strong className="mt-4 block text-lg font-black">{label}</strong><span className="mt-1 block text-xs font-semibold text-slate-500">{detail}</span></button>)}</div></div>}
            {step === 2 && <div><StepTitle title="When do you need the vehicle?" subtitle="Add the actual pickup and return dates for a useful handoff." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><DateField label="Pickup date" value={plan.pickupDate} onChange={(value) => setPlan((p) => ({ ...p, pickupDate: value, dropoffDate: p.dropoffDate && p.dropoffDate < value ? "" : p.dropoffDate }))} /><DateField label="Return date" value={plan.dropoffDate} min={plan.pickupDate || undefined} onChange={(value) => setPlan((p) => ({ ...p, dropoffDate: value }))} /></div></div>}
            {step === 3 && <div><StepTitle title="How much space do you need?" subtitle="Party size and luggage can change which fleets are a good fit." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Counter label="Travelers" icon={UsersRound} value={plan.travelers} min={1} max={12} onChange={(travelers) => setPlan((p) => ({ ...p, travelers }))} /><Counter label="Large bags" icon={Briefcase} value={plan.luggage} min={0} max={12} onChange={(luggage) => setPlan((p) => ({ ...p, luggage }))} /></div></div>}
            {step === 4 && <div><StepTitle title="What vehicle fits the trip?" subtitle="Choose one or let the planner recommend a class." /><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{VEHICLES.map(({ value, label, detail }) => <button key={value} type="button" onClick={() => setPlan((p) => ({ ...p, vehicleNeed: value }))} className={`rounded-[22px] border p-4 text-left ${plan.vehicleNeed === value ? "border-[#0f766e] bg-[#eaf8f5]" : "border-[#dce7e4] bg-white"}`}><span className="flex items-center gap-2"><CarFront size={17} className="text-[#0f766e]" /><strong className="text-sm font-black">{label}</strong></span><span className="mt-2 block text-xs font-semibold text-slate-500">{detail}</span></button>)}</div></div>}
            {step === 5 && <div><StepTitle title="Best matches for your trip" subtitle="Ranked from our verified directory. This is a fit score, not live inventory or a price quote." /><div className="mt-6 rounded-[28px] bg-[#032f2d] p-6 text-white"><p className="vi-eyebrow text-[#f5c451]">Recommended vehicle</p><h3 className="vi-display mt-2 text-4xl font-bold text-[#73e3d9]">{recommendation.label}</h3><p className="mt-3 text-sm font-semibold leading-6 text-white/68">{recommendation.reason}</p></div><div className="mt-5 grid gap-3">{matches.slice(0, 3).map((match, index) => <article key={match.operator.id} className="rounded-[24px] border border-[#d7e4e0] bg-white p-5 shadow-[0_10px_30px_rgba(3,47,45,.05)]"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#f5c451] text-xs font-black text-[#032f2d]">{index + 1}</span><div><p className="text-[8px] font-black uppercase tracking-[.12em] text-[#0f766e]">{index === 0 ? "Best fit" : "Strong match"}</p><h4 className="text-lg font-black text-[#032f2d]">{match.operator.name}</h4></div></div><p className="mt-2 flex items-center gap-1 text-xs font-bold text-slate-500"><MapPin size={13} /> {match.operator.location}</p></div><Star className="h-5 w-5 fill-[#f5c451] text-[#f5c451]" /></div><div className="mt-4 flex flex-wrap gap-2">{match.reasons.map((reason) => <span key={reason} className="rounded-full bg-[#eaf8f5] px-3 py-1.5 text-[8px] font-black uppercase tracking-[.08em] text-[#0f766e]">{reason}</span>)}</div><div className="mt-5 flex flex-wrap gap-2"><a href={match.operator.website} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[#032f2d] px-4 text-[8px] font-black uppercase tracking-[.11em] text-white">Check operator <ExternalLink size={13} /></a><Link href="#operators" className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#cfe0dc] px-4 text-[8px] font-black uppercase tracking-[.11em] text-[#0f766e]">Full directory <ArrowRight size={13} /></Link></div></article>)}</div><div className="mt-5"><Link href={`/concierge?open=true&prompt=${encodeURIComponent(conciergePrompt)}`} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#f5c451] px-6 text-[9px] font-black uppercase tracking-[.14em] text-[#032f2d]"><Sparkles size={15} /> Compare these with Concierge</Link></div></div>}
          </div>
          <div className="mt-7 flex items-center justify-between border-t border-[#e0e9e6] pt-6"><button type="button" onClick={() => setStep((s) => Math.max(0, s - 1))} disabled={step === 0} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#d7e4e0] px-5 text-[9px] font-black uppercase tracking-[.12em] disabled:opacity-35"><ArrowLeft size={15} /> Back</button>{step < 5 ? <button type="button" onClick={() => canContinue && setStep((s) => Math.min(5, s + 1))} disabled={!canContinue} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#032f2d] px-6 text-[9px] font-black uppercase tracking-[.13em] text-white disabled:bg-slate-300">Continue <ArrowRight size={15} className="text-[#f5c451]" /></button> : <button type="button" onClick={() => { setPlan(INITIAL_PLAN); setStep(0); }} className="inline-flex min-h-11 items-center rounded-full border border-[#b8d9d3] bg-[#eaf8f5] px-6 text-[9px] font-black uppercase tracking-[.13em] text-[#0f766e]">Start over</button>}</div>
        </div>
        <aside className="border-t border-[#d8e5e1] bg-[#f0f7f5] p-6 lg:border-l lg:border-t-0 lg:p-8"><p className="vi-eyebrow text-[#0f766e]">Trip summary</p><h3 className="vi-display mt-2 text-2xl font-bold">Your rental brief</h3><div className="mt-6 space-y-3"><SummaryRow icon={MapPin} label="Island" value={plan.island ? islandLabel(plan.island) : "Not selected"} ready={!!plan.island} /><SummaryRow icon={Plane} label="Arrival" value={plan.arrival ? arrivalLabel(plan.arrival) : "Not selected"} ready={!!plan.arrival} /><SummaryRow icon={CalendarDays} label="Dates" value={plan.pickupDate && plan.dropoffDate ? `${formatDate(plan.pickupDate)} – ${formatDate(plan.dropoffDate)}` : "Add pickup + return"} ready={!!(plan.pickupDate && plan.dropoffDate)} /><SummaryRow icon={UsersRound} label="Party" value={`${plan.travelers} travelers · ${plan.luggage} bags`} ready={step >= 3} /><SummaryRow icon={CarFront} label="Vehicle" value={step >= 4 ? recommendation.label : "We’ll recommend one"} ready={step >= 4} /></div>{step === 5 && matches[0] && <div className="mt-7 rounded-[24px] bg-[#032f2d] p-5 text-white"><p className="vi-eyebrow text-[#f5c451]">Top operator match</p><p className="mt-2 text-lg font-black">{matches[0].operator.name}</p><p className="mt-2 text-xs font-semibold leading-5 text-white/65">{matches[0].reasons.join(" · ")}</p></div>}</aside>
      </div>
    </div>
  </section>;
}

function ChoiceStep({ title, subtitle, options }: { title: string; subtitle: string; options: Array<{ value: string; label: string; detail: string; selected: boolean; onClick: () => void }> }) { return <div><StepTitle title={title} subtitle={subtitle} /><div className="mt-6 grid gap-3 sm:grid-cols-3">{options.map((o) => <button key={o.value} type="button" onClick={o.onClick} className={`rounded-[24px] border p-5 text-left ${o.selected ? "border-[#0f766e] bg-[#eaf8f5]" : "border-[#dce7e4] bg-white"}`}><strong className="block text-lg font-black">{o.label}</strong><span className="mt-2 block text-xs font-semibold text-slate-500">{o.detail}</span>{o.selected && <span className="mt-4 inline-flex items-center gap-1 text-[9px] font-black uppercase text-[#0f766e]"><Check size={14} /> Selected</span>}</button>)}</div></div>; }
function StepTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div><h3 className="vi-display text-3xl font-bold sm:text-4xl">{title}</h3><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-slate-600">{subtitle}</p></div>; }
function DateField({ label, value, min, onChange }: { label: string; value: string; min?: string; onChange: (value: string) => void }) { const today = new Date().toISOString().slice(0, 10); return <label className="rounded-[24px] border border-[#dce7e4] bg-white p-5"><span className="text-xs font-black uppercase tracking-[.11em] text-[#49615e]">{label}</span><input type="date" value={value} min={min || today} onChange={(e) => onChange(e.target.value)} className="mt-4 w-full rounded-2xl border border-[#cfded9] bg-[#f8fbfa] px-4 py-3 font-bold" /></label>; }
function Counter({ label, icon: Icon, value, min, max, onChange }: { label: string; icon: typeof UsersRound; value: number; min: number; max: number; onChange: (value: number) => void }) { return <div className="rounded-[24px] border border-[#dce7e4] bg-white p-5"><span className="flex items-center gap-2 text-xs font-black uppercase text-[#49615e]"><Icon size={16} /> {label}</span><div className="mt-5 flex items-center justify-between"><button type="button" onClick={() => onChange(Math.max(min, value - 1))} className="grid h-12 w-12 place-items-center rounded-full border text-2xl">−</button><strong className="vi-display text-5xl">{value}</strong><button type="button" onClick={() => onChange(Math.min(max, value + 1))} className="grid h-12 w-12 place-items-center rounded-full bg-[#032f2d] text-2xl text-white">+</button></div></div>; }
function SummaryRow({ icon: Icon, label, value, ready }: { icon: typeof MapPin; label: string; value: string; ready: boolean }) { return <div className="flex items-start gap-3 rounded-2xl border border-[#d8e5e1] bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf8f5] text-[#0f766e]"><Icon size={16} /></span><div><p className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className={`mt-1 text-sm font-black ${ready ? "text-[#032f2d]" : "text-slate-400"}`}>{value}</p></div></div>; }
function getStepReady(step: number, p: RentalPlan) { if (step === 0) return !!p.island; if (step === 1) return !!p.arrival; if (step === 2) return !!(p.pickupDate && p.dropoffDate && p.dropoffDate >= p.pickupDate); return true; }
function getRecommendation(p: RentalPlan): { label: string; reason: string; vehicle: CarRentalVehicleNeed } { if (p.vehicleNeed !== "auto") { const v = VEHICLES.find((x) => x.value === p.vehicleNeed)!; return { label: v.label, reason: `You selected ${v.label}; we’ll rank operators that list this class.`, vehicle: p.vehicleNeed }; } if (p.travelers >= 7 || p.luggage >= 7) return { label: "Passenger van", reason: "Passenger and cargo space should take priority for this group.", vehicle: "van" }; if (p.island === "stj") return { label: "Jeep / 4x4", reason: "St. John’s grades, tight roads, and villa access make a 4x4-oriented fleet a strong starting point.", vehicle: "jeep" }; if (p.travelers >= 4 || p.luggage >= 4) return { label: "SUV", reason: "Your group and luggage are better matched to a roomier SUV.", vehicle: "suv" }; return { label: "Compact / midsize car", reason: "A regular car is an efficient starting point for a smaller party with lighter luggage.", vehicle: "car" }; }
function buildConciergePrompt(p: RentalPlan, vehicle: string, operators: string[]) { return `Help me finish this USVI rental. Island: ${islandLabel(p.island)}. Arrival: ${arrivalLabel(p.arrival)}. Pickup: ${p.pickupDate}. Return: ${p.dropoffDate}. Travelers: ${p.travelers}. Bags: ${p.luggage}. Vehicle: ${vehicle}. Top directory matches: ${operators.join(", ")}. Compare pickup convenience, total price, deposit, insurance, fuel, cancellation, ferry restrictions, parking, and after-hours return. Do not claim live availability unless confirmed.`; }
function islandLabel(v: RentalPlan["island"]) { return v === "stt" ? "St. Thomas" : v === "stj" ? "St. John" : v === "stx" ? "St. Croix" : "Not selected"; }
function arrivalLabel(v: RentalPlan["arrival"]) { return v === "airport" ? "Airport arrival" : v === "ferry" ? "Ferry arrival" : v === "local" ? "Already on island" : "Not selected"; }
function formatDate(v: string) { return v ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${v}T12:00:00`)) : ""; }
