import { useEffect, useMemo, useState } from "react";
import {
  collection,
  doc,
  getDocs,
  orderBy,
  query,
  updateDoc,
} from "firebase/firestore";
import { Car, CheckCircle2, Clock, Landmark, Mail, RefreshCw } from "lucide-react";

import { db } from "../../firebase";

type LeadStatus =
  | "new"
  | "contacted"
  | "quoted"
  | "booked"
  | "completed"
  | "cancelled";

type TourLead = {
  id: string;
  siteId?: string;
  siteName: string;
  island: string;
  intent: "tour" | "ride" | "bundle";
  customerName?: string | null;
  customerEmail?: string | null;
  userId?: string | null;
  estimatedValue?: number;
  source?: string;
  status: LeadStatus;
  createdAt?: {
    seconds?: number;
  };
};

const STATUS_OPTIONS: LeadStatus[] = [
  "new",
  "contacted",
  "quoted",
  "booked",
  "completed",
  "cancelled",
];

function formatDate(lead: TourLead) {
  if (!lead.createdAt?.seconds) return "Recently";
  return new Date(lead.createdAt.seconds * 1000).toLocaleString();
}

function islandLabel(value: string) {
  if (value === "st_thomas" || value === "stt") return "St. Thomas";
  if (value === "st_john" || value === "stj") return "St. John";
  if (value === "st_croix" || value === "stx") return "St. Croix";
  if (value === "water_island" || value === "wat") return "Water Island";
  return value || "USVI";
}

export default function TourLeadsPage() {
  const [leads, setLeads] = useState<TourLead[]>([]);
  const [loading, setLoading] = useState(true);

  async function loadLeads() {
    setLoading(true);

    const snap = await getDocs(
      query(collection(db, "tourLeads"), orderBy("createdAt", "desc")),
    );

    setLeads(
      snap.docs.map((item) => ({
        id: item.id,
        ...(item.data() as Omit<TourLead, "id">),
      })),
    );

    setLoading(false);
  }

  async function updateStatus(id: string, status: LeadStatus) {
    await updateDoc(doc(db, "tourLeads", id), {
      status,
      updatedAt: new Date(),
    });

    setLeads((current) =>
      current.map((lead) => (lead.id === id ? { ...lead, status } : lead)),
    );
  }

  useEffect(() => {
    void loadLeads();
  }, []);

  const totals = useMemo(() => {
    const estimatedRevenue = leads.reduce(
      (sum, lead) => sum + Number(lead.estimatedValue || 0),
      0,
    );

    return {
      total: leads.length,
      new: leads.filter((lead) => lead.status === "new").length,
      booked: leads.filter((lead) => lead.status === "booked").length,
      completed: leads.filter((lead) => lead.status === "completed").length,
      estimatedRevenue,
    };
  }, [leads]);

  return (
    <main className="min-h-screen bg-[#071216] px-4 py-8 text-white">
      <section className="mx-auto max-w-7xl">
        <header className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-xs font-black uppercase tracking-[0.35em] text-emerald-300">
              Revenue Dashboard
            </p>
            <h1 className="mt-2 font-serif text-4xl font-black">
              Tour Leads
            </h1>
            <p className="mt-2 max-w-2xl text-sm text-white/60">
              Manage historic-site tour requests, taxi leads, and bundled visitor
              experiences generated by VI Guide.
            </p>
          </div>

          <button
            type="button"
            onClick={() => void loadLeads()}
            className="flex items-center gap-2 rounded-2xl bg-emerald-400 px-5 py-3 text-sm font-black text-[#022c22]"
          >
            <RefreshCw className="h-4 w-4" />
            Refresh
          </button>
        </header>

        <div className="mt-8 grid gap-4 md:grid-cols-4">
          <Metric title="Total Leads" value={totals.total} icon={Landmark} />
          <Metric title="New" value={totals.new} icon={Clock} />
          <Metric title="Booked" value={totals.booked} icon={CheckCircle2} />
          <Metric
            title="Est. Value"
            value={`$${totals.estimatedRevenue}`}
            icon={Car}
          />
        </div>

        <section className="mt-8 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.06] shadow-2xl">
          <div className="border-b border-white/10 px-6 py-4">
            <h2 className="text-xl font-black">Latest Requests</h2>
          </div>

          {loading ? (
            <div className="p-8 text-white/60">Loading leads...</div>
          ) : leads.length === 0 ? (
            <div className="p-8 text-white/60">
              No leads yet. Open a historic site, tap Book Tour, and the first
              lead will appear here.
            </div>
          ) : (
            <div className="divide-y divide-white/10">
              {leads.map((lead) => (
                <div
                  key={lead.id}
                  className="grid gap-4 p-5 lg:grid-cols-[1.4fr_1fr_1fr_auto]"
                >
                  <div>
                    <p className="text-lg font-black">{lead.siteName}</p>
                    <p className="mt-1 text-sm text-white/55">
                      {islandLabel(lead.island)} · {lead.intent.toUpperCase()} ·{" "}
                      {formatDate(lead)}
                    </p>

                    <div className="mt-3 flex flex-wrap gap-2">
                      <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">
                        ${lead.estimatedValue || 0} estimated
                      </span>
                      <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-white/70">
                        {lead.source || "historic-site-concierge"}
                      </span>
                    </div>
                  </div>

                  <div>
                    <p className="text-xs font-black uppercase tracking-[0.2em] text-white/40">
                      Visitor
                    </p>
                    <p className="mt-2 font-bold">
                      {lead.customerName || "Guest Visitor"}
                    </p>
                    {lead.customerEmail ? (
                      <p className="mt-1 flex items-center gap-2 text-sm text-white/55">
                        <Mail className="h-4 w-4" />
                        {lead.customerEmail}
                      </p>
                    ) : (
                      <p className="mt-1 text-sm text-white/45">
                        No email captured
                      </p>
                    )}
                  </div>

                  <div>
                    <p className="text-xs font-black uppercase tracking-[0.2em] text-white/40">
                      Status
                    </p>
                    <select
                      value={lead.status}
                      onChange={(event) =>
                        void updateStatus(
                          lead.id,
                          event.target.value as LeadStatus,
                        )
                      }
                      className="mt-2 w-full rounded-xl border border-white/10 bg-[#020814] px-3 py-3 text-sm font-bold text-white"
                    >
                      {STATUS_OPTIONS.map((status) => (
                        <option key={status} value={status}>
                          {status}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="flex items-center">
                    <button
                      type="button"
                      className="rounded-2xl bg-white px-5 py-3 text-xs font-black uppercase tracking-[0.16em] text-[#071216]"
                    >
                      Open
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </section>
    </main>
  );
}

function Metric({
  title,
  value,
  icon: Icon,
}: {
  title: string;
  value: string | number;
  icon: typeof Landmark;
}) {
  return (
    <div className="rounded-[2rem] border border-white/10 bg-white/[0.07] p-5 shadow-2xl">
      <div className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-400 text-[#022c22]">
        <Icon className="h-6 w-6" />
      </div>
      <p className="mt-4 text-sm font-bold text-white/55">{title}</p>
      <p className="mt-1 text-3xl font-black">{value}</p>
    </div>
  );
}