// Auto-updated historic sites.
// Generated by scripts/apply-final-historic-site-coordinates.ts.

export type IslandCode = "st_thomas" | "st_john" | "st_croix" | "water_island";

export type HistoricSite = {
  id: string;
  name: string;
  island?: IslandCode | string;
  type?: string;
  category?: string;
  estate?: string;
  description?: string;
  history?: string;
  significance?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  imageUrl?: string;
  coverImage?: string;
  thumbnailUrl?: string;
  relatedEstates?: string[];
  relatedArchives?: string[];
  relatedDictionaryEntries?: string[];
  tags?: string[];
  source?: string;
  [key: string]: unknown;
};

export const historicSites: HistoricSite[] = [
  {
    "id": "nrhp-stj-annaberg-historic-district",
    "name": "Annaberg Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Leinster Bay",
    "description": "Annaberg Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/annaberg.svg",
    "coverImage": "/images/dictionary/annaberg.svg",
    "thumbnailUrl": "/images/dictionary/annaberg.svg",
    "relatedEstates": [
      "Leinster Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-bethlehem-middle-works-historic-district",
    "name": "Bethlehem Middle Works Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Bethlehem",
    "description": "Bethlehem Middle Works Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1988.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-bethlehem-middle-works-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-bethlehem-middle-works-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-bethlehem-middle-works-historic-district.jpg",
    "relatedEstates": [
      "Bethlehem"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "industrial",
      "sugar",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-bordeaux",
    "name": "Bordeaux",
    "island": "st_thomas",
    "type": "historic-site",
    "category": "historic",
    "estate": "Bordeaux",
    "description": "Bordeaux is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.360099,
      "lng": -65.017106
    },
    "imageUrl": "/images/dictionary/bordeaux.svg",
    "coverImage": "/images/dictionary/bordeaux.svg",
    "thumbnailUrl": "/images/dictionary/bordeaux.svg",
    "relatedEstates": [
      "Bordeaux"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-brown-bay-plantation-historic-district",
    "name": "Brown Bay Plantation Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Brown Bay",
    "description": "Brown Bay Plantation Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/brown-bay.svg",
    "coverImage": "/images/dictionary/brown-bay.svg",
    "thumbnailUrl": "/images/dictionary/brown-bay.svg",
    "relatedEstates": [
      "Brown Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-catherineberg-jockumsdahl-herman-farm",
    "name": "Catherineberg-Jockumsdahl-Herman Farm",
    "island": "st_john",
    "type": "plantation-ruins",
    "category": "historic",
    "estate": "Catherineberg",
    "description": "Catherineberg-Jockumsdahl-Herman Farm is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-catherineberg-jockumsdahl-herman-farm.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-catherineberg-jockumsdahl-herman-farm.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-catherineberg-jockumsdahl-herman-farm.jpg",
    "relatedEstates": [
      "Catherineberg"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-charlotte-amalie-historic-district",
    "name": "Charlotte Amalie Historic District",
    "island": "st_thomas",
    "type": "historic-district",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "Charlotte Amalie Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/charlotte-amalie.jpg",
    "coverImage": "/images/dictionary/charlotte-amalie.jpg",
    "thumbnailUrl": "/images/dictionary/charlotte-amalie.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "urban-history",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-christiansted-historic-district",
    "name": "Christiansted Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Christiansted Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/christiansted.svg",
    "coverImage": "/images/dictionary/christiansted.svg",
    "thumbnailUrl": "/images/dictionary/christiansted.svg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "urban-history",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-christiansted-national-historic-site",
    "name": "Christiansted National Historic Site",
    "island": "st_croix",
    "type": "national-historic-site",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Christiansted National Historic Site is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1966.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/christiansted.svg",
    "coverImage": "/images/dictionary/christiansted.svg",
    "thumbnailUrl": "/images/dictionary/christiansted.svg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "nps",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-cinnamon-bay-plantation",
    "name": "Cinnamon Bay Plantation",
    "island": "st_john",
    "type": "plantation-ruins",
    "category": "historic",
    "estate": "Cinnamon Bay",
    "description": "Cinnamon Bay Plantation is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/beaches/cinnamon-bay.svg",
    "coverImage": "/images/beaches/cinnamon-bay.svg",
    "thumbnailUrl": "/images/beaches/cinnamon-bay.svg",
    "relatedEstates": [
      "Cinnamon Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-coakley-bay-estate",
    "name": "Coakley Bay Estate",
    "island": "st_croix",
    "type": "plantation-site",
    "category": "historic",
    "estate": "Coakley Bay",
    "description": "Coakley Bay Estate is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/coakley-bay.svg",
    "coverImage": "/images/dictionary/coakley-bay.svg",
    "thumbnailUrl": "/images/dictionary/coakley-bay.svg",
    "relatedEstates": [
      "Coakley Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-columbus-landing-site",
    "name": "Columbus Landing Site",
    "island": "st_croix",
    "type": "archaeological-site",
    "category": "historic",
    "estate": "Salt River Bay",
    "description": "Columbus Landing Site is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1966.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-columbus-landing-site.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-columbus-landing-site.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-columbus-landing-site.jpg",
    "relatedEstates": [
      "Salt River Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "salt-river",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-danish-west-india-and-guinea-company-warehouse",
    "name": "Danish West India and Guinea Company Warehouse",
    "island": "st_croix",
    "type": "warehouse",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Danish West India and Guinea Company Warehouse is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1974.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-danish-west-india-and-guinea-company-warehouse.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-danish-west-india-and-guinea-company-warehouse.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-danish-west-india-and-guinea-company-warehouse.jpg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "danish",
      "commerce",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-dennis-bay-historic-district",
    "name": "Dennis Bay Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Dennis Bay",
    "description": "Dennis Bay Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/estate/dennis-bay-hawknest.svg",
    "coverImage": "/images/estate/dennis-bay-hawknest.svg",
    "thumbnailUrl": "/images/estate/dennis-bay-hawknest.svg",
    "relatedEstates": [
      "Dennis Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-diamond-school",
    "name": "Diamond School",
    "island": "st_croix",
    "type": "school",
    "category": "historic",
    "estate": "Diamond",
    "description": "Diamond School is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-diamond-school.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-diamond-school.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-diamond-school.jpg",
    "relatedEstates": [
      "Diamond"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "school",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-emmaus-moravian-church-and-manse",
    "name": "Emmaus Moravian Church and Manse",
    "island": "st_john",
    "type": "church",
    "category": "historic",
    "estate": "Coral Bay",
    "description": "Emmaus Moravian Church and Manse is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1977.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-emmaus-moravian-church-and-manse.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-emmaus-moravian-church-and-manse.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-emmaus-moravian-church-and-manse.jpg",
    "relatedEstates": [
      "Coral Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "moravian",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-enighed",
    "name": "Enighed",
    "island": "st_john",
    "type": "historic-site",
    "category": "historic",
    "estate": "Cruz Bay",
    "description": "Enighed is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.328126,
      "lng": -64.793804
    },
    "imageUrl": "/images/dictionary/enighed.svg",
    "coverImage": "/images/dictionary/enighed.svg",
    "thumbnailUrl": "/images/dictionary/enighed.svg",
    "relatedEstates": [
      "Cruz Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-estate-beverhoudt",
    "name": "Estate Beverhoudt",
    "island": "st_john",
    "type": "plantation-site",
    "category": "historic",
    "estate": "Beverhoudt",
    "description": "Estate Beverhoudt is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/beverhoudt.svg",
    "coverImage": "/images/dictionary/beverhoudt.svg",
    "thumbnailUrl": "/images/dictionary/beverhoudt.svg",
    "relatedEstates": [
      "Beverhoudt"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-botany-bay",
    "name": "Estate Botany Bay",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Botany Bay",
    "description": "Estate Botany Bay is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.35374,
      "lng": -65.035911
    },
    "imageUrl": "/images/dictionary/botany-bay.svg",
    "coverImage": "/images/dictionary/botany-bay.svg",
    "thumbnailUrl": "/images/dictionary/botany-bay.svg",
    "relatedEstates": [
      "Botany Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-brewers-bay",
    "name": "Estate Brewers Bay",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Brewers Bay",
    "description": "Estate Brewers Bay is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.344734,
      "lng": -64.977824
    },
    "imageUrl": "/images/beaches/brewers-bay.jpg",
    "coverImage": "/images/beaches/brewers-bay.jpg",
    "thumbnailUrl": "/images/beaches/brewers-bay.jpg",
    "relatedEstates": [
      "Brewers Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-butlers-bay",
    "name": "Estate Butler's Bay",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Butler's Bay",
    "description": "Estate Butler's Bay is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.75361,
      "lng": -64.880169
    },
    "imageUrl": "/images/historicSite/nrhp-stx-estate-butlers-bay.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-estate-butlers-bay.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-estate-butlers-bay.jpg",
    "relatedEstates": [
      "Butler's Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-estate-carolina-sugar-plantation",
    "name": "Estate Carolina Sugar Plantation",
    "island": "st_john",
    "type": "plantation-ruins",
    "category": "historic",
    "estate": "Carolina",
    "description": "Estate Carolina Sugar Plantation is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-estate-carolina-sugar-plantation.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-estate-carolina-sugar-plantation.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-estate-carolina-sugar-plantation.jpg",
    "relatedEstates": [
      "Carolina"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "sugar",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-grove-place",
    "name": "Estate Grove Place",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Grove Place",
    "description": "Estate Grove Place is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.727104,
      "lng": -64.824146
    },
    "imageUrl": "/images/estate/grove-place.svg",
    "coverImage": "/images/estate/grove-place.svg",
    "thumbnailUrl": "/images/estate/grove-place.svg",
    "relatedEstates": [
      "Grove Place"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-hafensight",
    "name": "Estate Hafensight",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Havensight",
    "description": "Estate Hafensight is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.329422,
      "lng": -64.92157
    },
    "imageUrl": "/images/estate/hafensight.svg",
    "coverImage": "/images/estate/hafensight.svg",
    "thumbnailUrl": "/images/estate/hafensight.svg",
    "relatedEstates": [
      "Havensight"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-hogansborg",
    "name": "Estate Hogansborg",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Hogansborg",
    "description": "Estate Hogansborg is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.7091,
      "lng": -64.8463
    },
    "imageUrl": "/images/historicSite/nrhp-stx-estate-hogansborg.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-estate-hogansborg.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-estate-hogansborg.jpg",
    "relatedEstates": [
      "Hogansborg"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-judiths-fancy",
    "name": "Estate Judith's Fancy",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Judith's Fancy",
    "description": "Estate Judith's Fancy is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.776914,
      "lng": -64.747497
    },
    "imageUrl": "/images/historicSite/nrhp-stx-estate-judiths-fancy.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-estate-judiths-fancy.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-estate-judiths-fancy.jpg",
    "relatedEstates": [
      "Judith's Fancy"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-la-reine",
    "name": "Estate La Reine",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "La Reine",
    "description": "Estate La Reine is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1980.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.7319,
      "lng": -64.772688
    },
    "imageUrl": "/images/estate/la-reine.svg",
    "coverImage": "/images/estate/la-reine.svg",
    "thumbnailUrl": "/images/estate/la-reine.svg",
    "relatedEstates": [
      "La Reine"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-little-princess",
    "name": "Estate Little Princess",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Little Princess",
    "description": "Estate Little Princess is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1980.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.753763,
      "lng": -64.726016
    },
    "imageUrl": "/images/dictionary/little-princess.svg",
    "coverImage": "/images/dictionary/little-princess.svg",
    "thumbnailUrl": "/images/dictionary/little-princess.svg",
    "relatedEstates": [
      "Little Princess"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-mount-victory",
    "name": "Estate Mount Victory",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Mount Victory",
    "description": "Estate Mount Victory is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.751862,
      "lng": -64.86838
    },
    "imageUrl": "/images/estate/mount-victory.svg",
    "coverImage": "/images/estate/mount-victory.svg",
    "thumbnailUrl": "/images/estate/mount-victory.svg",
    "relatedEstates": [
      "Mount Victory"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-neltjeberg",
    "name": "Estate Neltjeberg",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Neltjeberg",
    "description": "Estate Neltjeberg is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.368371,
      "lng": -64.969219
    },
    "imageUrl": "/images/dictionary/neltjeberg.svg",
    "coverImage": "/images/dictionary/neltjeberg.svg",
    "thumbnailUrl": "/images/dictionary/neltjeberg.svg",
    "relatedEstates": [
      "Neltjeberg"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-niesky",
    "name": "Estate Niesky",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Niesky",
    "description": "Estate Niesky is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.338611,
      "lng": -64.951667
    },
    "imageUrl": "/images/historicSite/nrhp-stt-estate-niesky.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-estate-niesky.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-estate-niesky.jpg",
    "relatedEstates": [
      "Niesky"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-estate-perseverance",
    "name": "Estate Perseverance",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Perseverance",
    "description": "Estate Perseverance is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.353365,
      "lng": -64.997181
    },
    "imageUrl": "/images/dictionary/perseverance.svg",
    "coverImage": "/images/dictionary/perseverance.svg",
    "thumbnailUrl": "/images/dictionary/perseverance.svg",
    "relatedEstates": [
      "Perseverance"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-prosperity",
    "name": "Estate Prosperity",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Prosperity",
    "description": "Estate Prosperity is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.72571,
      "lng": -64.886395
    },
    "imageUrl": "/images/dictionary/prosperity.svg",
    "coverImage": "/images/dictionary/prosperity.svg",
    "thumbnailUrl": "/images/dictionary/prosperity.svg",
    "relatedEstates": [
      "Prosperity"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-saint-george-historic-district",
    "name": "Estate Saint George Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Saint George",
    "description": "Estate Saint George Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1986.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/saint-george-beck.svg",
    "coverImage": "/images/dictionary/saint-george-beck.svg",
    "thumbnailUrl": "/images/dictionary/saint-george-beck.svg",
    "relatedEstates": [
      "Saint George"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-estate-st-john",
    "name": "Estate St. John",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "St. John",
    "description": "Estate St. John is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.764892,
      "lng": -64.745118
    },
    "imageUrl": "/images/historicSite/nrhp-stx-estate-st-john.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-estate-st-john.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-estate-st-john.jpg",
    "relatedEstates": [
      "St. John"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-fort-frederick",
    "name": "Fort Frederick",
    "island": "st_croix",
    "type": "fort",
    "category": "historic",
    "estate": "Frederiksted",
    "description": "Fort Frederick is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1996.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-fort-frederick.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-fort-frederick.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-fort-frederick.jpg",
    "relatedEstates": [
      "Frederiksted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "fort",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-fortsberg",
    "name": "Fortsberg",
    "island": "st_john",
    "type": "fort",
    "category": "historic",
    "estate": "Coral Bay",
    "description": "Fortsberg is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/estate/fortsberg.svg",
    "coverImage": "/images/estate/fortsberg.svg",
    "thumbnailUrl": "/images/estate/fortsberg.svg",
    "relatedEstates": [
      "Coral Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "fort",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-frederiksted-historic-district",
    "name": "Frederiksted Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Frederiksted",
    "description": "Frederiksted Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/frederiksted.svg",
    "coverImage": "/images/dictionary/frederiksted.svg",
    "thumbnailUrl": "/images/dictionary/frederiksted.svg",
    "relatedEstates": [
      "Frederiksted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "urban-history",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-friedensfeld-midlands-moravian-church-and-manse",
    "name": "Friedensfeld Midlands Moravian Church and Manse",
    "island": "st_croix",
    "type": "church",
    "category": "historic",
    "estate": "Midlands",
    "description": "Friedensfeld Midlands Moravian Church and Manse is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-friedensfeld-midlands-moravian-church-and-manse.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-friedensfeld-midlands-moravian-church-and-manse.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-friedensfeld-midlands-moravian-church-and-manse.jpg",
    "relatedEstates": [
      "Midlands"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "moravian",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-friedensthal-mission",
    "name": "Friedensthal Mission",
    "island": "st_croix",
    "type": "mission",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Friedensthal Mission is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-friedensthal-mission.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-friedensthal-mission.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-friedensthal-mission.jpg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "moravian",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-ft-frederik-of-us-virgin-islands",
    "name": "Ft. Frederik of US Virgin Islands",
    "island": "st_croix",
    "type": "fort",
    "category": "historic",
    "estate": "Frederiksted",
    "description": "Ft. Frederik of US Virgin Islands is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1997.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-ft-frederik-of-us-virgin-islands.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-ft-frederik-of-us-virgin-islands.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-ft-frederik-of-us-virgin-islands.jpg",
    "relatedEstates": [
      "Frederiksted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "fort",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-green-kay",
    "name": "Green Kay",
    "island": "st_croix",
    "type": "island",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Green Kay is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-green-kay.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-green-kay.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-green-kay.jpg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "archaeology",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-hamburg-america-shipping-line-administrative-offices",
    "name": "Hamburg-America Shipping Line Administrative Offices",
    "island": "st_thomas",
    "type": "historic-building",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "Hamburg-America Shipping Line Administrative Offices is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-hamburg-america-shipping-line-administrative-offices.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-hamburg-america-shipping-line-administrative-offices.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-hamburg-america-shipping-line-administrative-offices.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "maritime",
      "commerce",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-hassel-island",
    "name": "Hassel Island",
    "island": "st_thomas",
    "type": "historic-district",
    "category": "historic",
    "estate": "Hassel Island",
    "description": "Hassel Island is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/hassel-island.svg",
    "coverImage": "/images/dictionary/hassel-island.svg",
    "thumbnailUrl": "/images/dictionary/hassel-island.svg",
    "relatedEstates": [
      "Hassel Island"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "maritime",
      "military",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-hassel-island-boundary-increase",
    "name": "Hassel Island Historic District (Boundary Increase)",
    "island": "st_thomas",
    "type": "historic-district",
    "category": "historic",
    "estate": "Hassel Island",
    "description": "Hassel Island Historic District (Boundary Increase) is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-hassel-island-boundary-increase.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-hassel-island-boundary-increase.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-hassel-island-boundary-increase.jpg",
    "relatedEstates": [
      "Hassel Island"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "maritime",
      "military",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-hermitage-plantation-historic-district",
    "name": "Hermitage Plantation Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Hurricane Hole",
    "description": "Hermitage Plantation Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/hermitage.svg",
    "coverImage": "/images/dictionary/hermitage.svg",
    "thumbnailUrl": "/images/dictionary/hermitage.svg",
    "relatedEstates": [
      "Hurricane Hole"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-jossie-gut-historic-district",
    "name": "Jossie Gut Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Reef Bay",
    "description": "Jossie Gut Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-jossie-gut-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-jossie-gut-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-jossie-gut-historic-district.jpg",
    "relatedEstates": [
      "Reef Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-lesperance-historic-district",
    "name": "L'Esperance Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Reef Bay",
    "description": "L'Esperance Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-lesperance-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-lesperance-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-lesperance-historic-district.jpg",
    "relatedEstates": [
      "Reef Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-la-grande-princesse-school",
    "name": "La Grande Princesse School",
    "island": "st_croix",
    "type": "school",
    "category": "historic",
    "estate": "La Grande Princesse",
    "description": "La Grande Princesse School is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-la-grande-princesse-school.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-la-grande-princesse-school.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-la-grande-princesse-school.jpg",
    "relatedEstates": [
      "La Grande Princesse"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "school",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-lameshur-plantation",
    "name": "Lameshur Plantation",
    "island": "st_john",
    "type": "plantation-ruins",
    "category": "historic",
    "estate": "Lameshur",
    "description": "Lameshur Plantation is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/lameshur.svg",
    "coverImage": "/images/dictionary/lameshur.svg",
    "thumbnailUrl": "/images/dictionary/lameshur.svg",
    "relatedEstates": [
      "Lameshur"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-liever-marches-bay-historic-district",
    "name": "Liever Marches Bay Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Brown Bay",
    "description": "Liever Marches Bay Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/liever-marches-bay.svg",
    "coverImage": "/images/dictionary/liever-marches-bay.svg",
    "thumbnailUrl": "/images/dictionary/liever-marches-bay.svg",
    "relatedEstates": [
      "Brown Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-lind-point-fort",
    "name": "Lind Point Fort",
    "island": "st_john",
    "type": "fort",
    "category": "historic",
    "estate": "Cruz Bay",
    "description": "Lind Point Fort is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-lind-point-fort.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-lind-point-fort.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-lind-point-fort.jpg",
    "relatedEstates": [
      "Cruz Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "fort",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-little-la-grange",
    "name": "Little La Grange",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Little La Grange",
    "description": "Little La Grange is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.724966,
      "lng": -64.865709
    },
    "imageUrl": "/images/estate/little-la-grange.svg",
    "coverImage": "/images/estate/little-la-grange.svg",
    "thumbnailUrl": "/images/estate/little-la-grange.svg",
    "relatedEstates": [
      "Little La Grange"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-mafolie-great-house",
    "name": "Mafolie Great House",
    "island": "st_thomas",
    "type": "great-house",
    "category": "historic",
    "estate": "Mafolie",
    "description": "Mafolie Great House is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-mafolie-great-house.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-mafolie-great-house.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-mafolie-great-house.jpg",
    "relatedEstates": [
      "Mafolie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "great-house",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-mary-point-estate",
    "name": "Mary Point Estate",
    "island": "st_john",
    "type": "estate",
    "category": "historic",
    "estate": "Mary Point",
    "description": "Mary Point Estate is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.368333,
      "lng": -64.741389
    },
    "imageUrl": "/images/dictionary/mary-point-estate.svg",
    "coverImage": "/images/dictionary/mary-point-estate.svg",
    "thumbnailUrl": "/images/dictionary/mary-point-estate.svg",
    "relatedEstates": [
      "Mary Point"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-more-hill-historic-district",
    "name": "More Hill Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "East End",
    "description": "More Hill Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-more-hill-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-more-hill-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-more-hill-historic-district.jpg",
    "relatedEstates": [
      "East End"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-new-herrnhut-moravian-church",
    "name": "New Herrnhut Moravian Church",
    "island": "st_thomas",
    "type": "church",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "New Herrnhut Moravian Church is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-new-herrnhut-moravian-church.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-new-herrnhut-moravian-church.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-new-herrnhut-moravian-church.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "moravian",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-reef-bay-great-house-historic-district",
    "name": "Reef Bay Great House Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Reef Bay",
    "description": "Reef Bay Great House Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-reef-bay-great-house-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-reef-bay-great-house-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-reef-bay-great-house-historic-district.jpg",
    "relatedEstates": [
      "Reef Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-reef-bay-sugar-factory-historic-district",
    "name": "Reef Bay Sugar Factory Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Reef Bay",
    "description": "Reef Bay Sugar Factory Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-reef-bay-sugar-factory-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-reef-bay-sugar-factory-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-reef-bay-sugar-factory-historic-district.jpg",
    "relatedEstates": [
      "Reef Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "sugar",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-richmond-prison-detention-and-workhouse",
    "name": "Richmond Prison Detention and Workhouse",
    "island": "st_croix",
    "type": "prison",
    "category": "historic",
    "estate": "Richmond",
    "description": "Richmond Prison Detention and Workhouse is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stx-richmond-prison-detention-and-workhouse.jpg",
    "coverImage": "/images/historicSite/nrhp-stx-richmond-prison-detention-and-workhouse.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stx-richmond-prison-detention-and-workhouse.jpg",
    "relatedEstates": [
      "Richmond"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "institutional",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-rustenberg-plantation-south-historic-district",
    "name": "Rustenberg Plantation South Historic District",
    "island": "st_john",
    "type": "historic-district",
    "category": "historic",
    "estate": "Cinnamon Bay",
    "description": "Rustenberg Plantation South Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-rustenberg-plantation-south-historic-district.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-rustenberg-plantation-south-historic-district.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-rustenberg-plantation-south-historic-district.jpg",
    "relatedEstates": [
      "Cinnamon Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-sion-hill",
    "name": "Sion Hill",
    "island": "st_croix",
    "type": "estate",
    "category": "historic",
    "estate": "Sion Hill",
    "description": "Sion Hill is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 17.734244,
      "lng": -64.743727
    },
    "imageUrl": "/images/dictionary/sion-hill.svg",
    "coverImage": "/images/dictionary/sion-hill.svg",
    "thumbnailUrl": "/images/dictionary/sion-hill.svg",
    "relatedEstates": [
      "Sion Hill"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-skytsborg",
    "name": "Skytsborg",
    "island": "st_thomas",
    "type": "tower",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "Skytsborg is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1991.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/skytsborg-tower.jpg",
    "coverImage": "/images/historicSite/skytsborg-tower.jpg",
    "thumbnailUrl": "/images/historicSite/skytsborg-tower.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "tower",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-slob-historic-district",
    "name": "Slob Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Christiansted",
    "description": "Slob Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1987.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/slob.svg",
    "coverImage": "/images/dictionary/slob.svg",
    "thumbnailUrl": "/images/dictionary/slob.svg",
    "relatedEstates": [
      "Christiansted"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "district",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-st-thomas-synagogue",
    "name": "St. Thomas Synagogue",
    "island": "st_thomas",
    "type": "synagogue",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "St. Thomas Synagogue is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1997.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/st-thomas-synagogue.jpg",
    "coverImage": "/images/historicSite/st-thomas-synagogue.jpg",
    "thumbnailUrl": "/images/historicSite/st-thomas-synagogue.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "synagogue",
      "jewish-history",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-st-thomas-synagogue-beracha",
    "name": "St. Thomas Synagogue--Beracha Veshalom Vegemiluth Hasadim",
    "island": "st_thomas",
    "type": "synagogue",
    "category": "historic",
    "estate": "Charlotte Amalie",
    "description": "St. Thomas Synagogue--Beracha Veshalom Vegemiluth Hasadim is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1997.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-st-thomas-synagogue-beracha.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-st-thomas-synagogue-beracha.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-st-thomas-synagogue-beracha.jpg",
    "relatedEstates": [
      "Charlotte Amalie"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "synagogue",
      "jewish-history",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-strawberry-hill-historic-district",
    "name": "Strawberry Hill Historic District",
    "island": "st_croix",
    "type": "historic-district",
    "category": "historic",
    "estate": "Strawberry Hill",
    "description": "Strawberry Hill Historic District is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1987.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/strawberry-hill.svg",
    "coverImage": "/images/dictionary/strawberry-hill.svg",
    "thumbnailUrl": "/images/dictionary/strawberry-hill.svg",
    "relatedEstates": [
      "Strawberry Hill"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "district",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stj-trunk-bay-sugar-factory",
    "name": "Trunk Bay Sugar Factory",
    "island": "st_john",
    "type": "sugar-factory",
    "category": "historic",
    "estate": "Trunk Bay",
    "description": "Trunk Bay Sugar Factory is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1981.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stj-trunk-bay-sugar-factory.jpg",
    "coverImage": "/images/historicSite/nrhp-stj-trunk-bay-sugar-factory.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stj-trunk-bay-sugar-factory.jpg",
    "relatedEstates": [
      "Trunk Bay"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "sugar",
      "st-john"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-tutu-plantation-house",
    "name": "Tutu Plantation House",
    "island": "st_thomas",
    "type": "plantation-house",
    "category": "historic",
    "estate": "Tutu",
    "description": "Tutu Plantation House is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/historicSite/nrhp-stt-tutu-plantation-house.jpg",
    "coverImage": "/images/historicSite/nrhp-stt-tutu-plantation-house.jpg",
    "thumbnailUrl": "/images/historicSite/nrhp-stt-tutu-plantation-house.jpg",
    "relatedEstates": [
      "Tutu"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stt-venus-hill",
    "name": "Venus Hill",
    "island": "st_thomas",
    "type": "estate",
    "category": "historic",
    "estate": "Venus Hill",
    "description": "Venus Hill is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1978.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": {
      "lat": 18.353333,
      "lng": -64.929444
    },
    "imageUrl": "/images/dictionary/venus-hill.svg",
    "coverImage": "/images/dictionary/venus-hill.svg",
    "thumbnailUrl": "/images/dictionary/venus-hill.svg",
    "relatedEstates": [
      "Venus Hill"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "estate",
      "st-thomas"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  },
  {
    "id": "nrhp-stx-whim",
    "name": "Whim",
    "island": "st_croix",
    "type": "plantation-museum",
    "category": "historic",
    "estate": "Whim",
    "description": "Whim is listed in the National Register of Historic Places for the U.S. Virgin Islands.",
    "history": "National Register of Historic Places listing year: 1976.",
    "significance": "Official National Register historic resource; enrich with nomination text, coordinates, images, and local interpretation.",
    "coordinates": null,
    "imageUrl": "/images/dictionary/whim.svg",
    "coverImage": "/images/dictionary/whim.svg",
    "thumbnailUrl": "/images/dictionary/whim.svg",
    "relatedEstates": [
      "Whim"
    ],
    "relatedArchives": [
      "National Register of Historic Places",
      "National Park Service"
    ],
    "tags": [
      "nrhp",
      "plantation",
      "museum",
      "st-croix"
    ],
    "source": "National Park Service — Virgin Islands National Register of Historic Places list"
  }
];

export const HISTORIC_SITES = historicSites;
export const historicSiteRecords = historicSites;
export const records = historicSites;

export default historicSites;
